### ISSUE TITLE
Post-processing for more than 7 algorithms

### ISSUE THREAD

**Issue by strickler** [numbbo/coco#1044]
Dear all,

I tried to run the post-processing for 8 algorithms, and then COCO throw this error.

"ECDFs of run lengths figures done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/__main__.py", line 296, in <module>
    rungeneric.main(args)
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric.py", line 276, in main
    rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungenericmany.py", line 386, in main
    genericsettings.verbose)
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/compall/pptables.py", line 375, in main
    tmp.append(i in tmptop[j] or (nalgs > 7 and algerts[i][j] <= 3. * refalgert[j]))
UnboundLocalError: local variable 'refalgert' referenced before assignment"

Has anyone got the same thing??
I am using the coco-1.1.1.

Thanks in advance,
Andrei

**Comment by brockho** [comment]
Dear Andrei,

Looking at line 375 of the code in [`pptables.py`](https://github.com/numbbo/coco/blob/master/code-postprocessing/bbob_pproc/compall/pptables.py#L363) together with lines 293/294/295, I can see that it is definitely a bug that you are experiencing, although it does not show up when I am trying with eight of our data sets (which is probably the reason why it was never caught so far).

Can you please confirm that it appears for the biobjective `bbob-biobj` test suite? Because for the single-objective case, the error should not appear at all (because `refalgert` is defined in this case in line 275).

We will correct this bug asap within the next release.

**Comment by strickler** [comment]
Dear Brockhoff,
Yes, I am trying on bbob-biobj test suite, that contains the 55 functions.

Thanks

**Comment by dtusar** [comment]
Dear all,

This issue was solved last week. But since the last release is from two weeks ago, the fix is not included in it. @brockho it worked for you, because you probably tried this on the development version where it's already fixed. I think it's time for a new release.

I will close this issue.

**Comment by brockho** [comment]
The release 1.1.2 is now available at https://github.com/numbbo/coco/releases/tag/v1.1.2
