### ISSUE TITLE
Post-processing to make a comparison of many algorithms

### ISSUE THREAD

**Issue by strickler** [numbbo/coco#1060]
Dear all,
I tried to compare eight algorithms, but it returns the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-1.1.1-py2.7.egg/bbob_pproc/__main__.py", line 301, in <module>
    rungeneric.main(args)
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-1.1.1-py2.7.egg/bbob_pproc/rungeneric.py", line 276, in main
    rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-1.1.1-py2.7.egg/bbob_pproc/rungenericmany.py", line 387, in main
    ([1,20,38] if (testbedsettings.current_testbed.name == testbedsettings.testbed_name_bi) else True))
  File "/home/andrei/.local/lib/python2.7/site-packages/bbob_pproc-1.1.1-py2.7.egg/bbob_pproc/compall/pptables.py", line 375, in main
    tmp.append(i in tmptop[j] or (nalgs > 7 and algerts[i][j] <= 3. * refalgert[j]))
UnboundLocalError: local variable 'refalgert' referenced before assignment

In issue #1044 I brought the same error, but  @dtusar mentioned that it will be fixed for the next release, and it does not happen, I guess. To be clear, I am using the release 1.1.2. 
Sorry if I open a new issue and the error seems the same, but if it was incorrect for my part, I can re-write this in #1044 .

Thanks in advance.

**Comment by dtusar** [comment]
Don't worry about opening a new issue. 
I noticed in the error above that the package 1.1.1 is still called. Probably you just need to go to the folder which includes the 1.1.2 release and call `python do.py install-postprocessing`. 

Please let me know if this works for you.

**Comment by strickler** [comment]
Hi @dtusar ,
Thanks for your answer. You are right.
I did not call the `install-postprocessing` command, and that is the point. 
Now, it generates a new error that I did not see in the post-processing yet.
----
Post-processing will generate comparison data in folder resultsNEW
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: ./exdata/NSGAII-U_on_bbob-biobj-001
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: ./exdata/NSGAII_on_bbob-biobj-001
log aRT1/aRT0 vs target function values...
  done (Mon Jun  6 12:34:01 2016).
ECDF runlength ratio graphs...
  done (Mon Jun  6 12:34:20 2016).
ECDF graphs per noise group...
  done (Mon Jun  6 12:34:27 2016).
ECDF runlength graphs per function group...
  done (Mon Jun  6 12:35:47 2016).
ECDF runlength graphs...
  done (Mon Jun  6 12:36:12 2016).
ECDF graphs per function...
  done (Mon Jun  6 12:40:12 2016).
Scatter plots...
  done (Mon Jun  6 12:41:28 2016).
Generating old tables (pptable2.py)...
  done (Mon Jun  6 12:41:29 2016).
Generating new tables (pptables.py)...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/__main__.py", line 300, in <module>
    rungeneric.main(args)
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/rungeneric.py", line 273, in main
    rungeneric2.main(genopts + ["-o", outputdir] + args)
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/rungeneric2.py", line 622, in main
    testbedsettings.testbed_name_bi) else True))
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/compall/pptables.py", line 657, in main
    with open(filename) as infile:
IOError: [Errno 2] No such file or directory: 'resultsNEW/templateBBOBmany.html'
----

Thanks in advance

**Comment by dtusar** [comment]
Thank you for reporting the issue. The fix will be included in the next release which will be available soon.
