### ISSUE TITLE
Postprocessing Error

### ISSUE THREAD

**Issue by lfmingo** [numbbo/coco#1090]
Running `python -m bbob_pproc exdata/RS_on_bbob` (on MacOS, pyton 2.7, numpy, matplotpy)

See error trace below.

-----------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/__main__.py", line 341, in <module>
    rungeneric.main(args)
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric.py", line 271, in main
    + ["-o", outputdir, alg])
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric1.py", line 281, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/pproc.py", line 1485, in __init__
    self.processIndexFile(name, verbose)
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/pproc.py", line 1556, in processIndexFile
    ds = DataSet(header, comment, data, indexFile, verbose)                    
  File "/Users/lfmingo/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/pproc.py", line 776, in __init__
    self.readfinalFminusFtarget.append(float(readfinalf))
ValueError: invalid literal for float(): 1,0e+01

**Comment by ttusar** [comment]
> ValueError: invalid literal for float(): 1,0e+01

It seems as if your data files have commas instead of dots as decimal symbols... Could you check?

**Comment by lfmingo** [comment]
SOLVED.... Add `export LC_ALL=en_US.UTF-8`  and `export LANG=en_US.UTF-8` to `/etc/profile`. And rerun tests again.
