### ISSUE TITLE
Python error for coco invalid literal for float(): 7.3e-01:31160|5.7e+00

### ISSUE THREAD

**Issue by AmerDraa** [numbbo/coco#1123]
```
Hello everyone, 

Would anybody help me please in finding out the cause of the following error ? :
**ValueError: invalid literal for float(): 7.3e-01:31160|5.7e+00**

I get the error from running the command: "rungeneric.py LSSDE9 CMA-CSA" , where LSSDE9 and CMA-CSA are the algorithms being compared using the Bbob platform. 

NB: the error does not occur with other result sets, gotten from the same program.

Here is the whole message I get:
C:\all>python C:\all\rungeneric.py LSSDE9 CMA-CSA
in_a_hurry like 1000 (should finally be set to zero)
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata\.\LSSDE9
  this might take several minutes.
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f1.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f10.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f11.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f12.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f13.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f14.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
C:\all\bbob_pproc\pproc.py:1407: UserWarning: same DataSet found twice, second one from ['.\\LSSDE9\\bbobexp_f15.info'] is disregarded
  warnings.warn("same DataSet found twice, second one from " + str(o.indexFiles) + " is disregarded")
Traceback (most recent call last):
  File "C:\all\rungeneric.py", line 308, in <module>
    res = main()
  File "C:\all\rungeneric.py", line 287, in main
    + ["-o", tmpoutputdir, alg])
  File "C:\all\bbob_pproc\rungeneric1.py", line 291, in main
    dsList = DataSetList(filelist, verbose)
  File "C:\all\bbob_pproc\pproc.py", line 1326, in __init__
    self.processIndexFile(name, verbose)
  File "C:\all\bbob_pproc\pproc.py", line 1387, in processIndexFile
    verbose))
  File "C:\all\bbob_pproc\pproc.py", line 705, in __init__
    self.readfinalFminusFtarget.append(float(readfinalf))
**ValueError: invalid literal for float(): 7.3e-01:31160|5.7e+00**

Thank you in advance
```

**Comment by brockho** [comment]
Hi,

From a first look, it seems as if for some reason your data files are corrupted. The typical entries in the `.info` files are something like `54:20000|5.3e-001` (instance number:max. number of funevals|smallest f-value reached). Seeing the `same DataSet found twice` warnings, my guess is that you had accidentally two algorithms running at the same time and they wrote to the same line.

If you can exclude this situation for sure, can you please send us the entire data set where the error occurred such that we can try to run the postprocessing on our side? Thanks.

**Comment by AmerDraa** [comment]
Hello brockho,

You are totally right, there were two algorithms working in parallel that used the same resultset folder.

Thank you so much, the error is corrected now.
