### ISSUE TITLE
nan return values

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1236]
The Schaffer functions f17 and 18 return in some cases `nan`, namely if `||x||>=8.7e+03`. This happens for any dimension of the `bbob` suite. It seems unavoidable to have `inf` as return value for too large values of `x`, but `nan` should be considered rather a bug than a feature. 

Specifically:
```python
import cocoex
suite = cocoex.Suite('bbob', '', '')
suite[240].name
    'BBOB suite problem f17 instance 1 in 2D'
suite[240]([-10520.64349836,  29080.37809758])
    nan
suite[255].name
    'BBOB suite problem f18 instance 1 in 2D'
suite[255]([-6036.27514618,  2238.47803003])
    nan
```

**Comment by nikohansen** [comment]
Much less frequently also the Rastrigin functions f3 and f15 return `nan`.  Specifically:

```python
import cocoex
suite = cocoex.Suite('bbob', '', '')
suite[37].name
  'BBOB suite problem f3 instance 53 in 2D'
suite[37]([ 46365.59841475,  86158.21134626])
  nan
 suite[224].name
    'BBOB suite problem f15 instance 60 in 2D'
suite[224]([ 17169.14667182, -84332.12817395])
    nan
```

**Comment by nikohansen** [comment]
The reason is that `sin(inf)` and `cos(inf)` result in `nan`, as they should. Now the functions check the argument of these and return `inf` in case (as they should).

**Comment by Yash-Pisat** [comment]
I am running Bayesian optimization with COCO framework. For smaller budget, I am able to run the experiment on bbob test suite. But when I am increasing the budget to 50, I am getting this error:

> Traceback (most recent call last):
  File "/Users/yash.pisat/Desktop/COCO/Experiments/Bay_opt_exp.py", line 204, in <module>
    train_x,train_y, mean_gp, variance_gp, acquisition_values_ei, model = fmin(problem, problem.lower_bounds, problem.upper_bounds, 2,"EI" )
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/Desktop/COCO/Experiments/Bay_opt_exp.py", line 98, in BO
    new_x, acq_value = optimize_acqf(
                       ^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/optim/optimize.py", line 563, in optimize_acqf
    return _optimize_acqf(opt_acqf_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/optim/optimize.py", line 584, in _optimize_acqf
    return _optimize_acqf_batch(opt_inputs=opt_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/optim/optimize.py", line 349, in _optimize_acqf_batch
    batch_candidates, batch_acq_values, ws = _optimize_batch_candidates()
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/optim/optimize.py", line 333, in _optimize_batch_candidates
    ) = opt_inputs.gen_candidates(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/generation/gen.py", line 252, in gen_candidates_scipy
    res = minimize_with_timeout(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/optim/utils/timeout.py", line 80, in minimize_with_timeout
    return optimize.minimize(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 71, in _compute_if_needed
    fg = self.fun(x, *args)
         ^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/envs/thesisvenv/lib/python3.11/site-packages/botorch/generation/gen.py", line 220, in f_np_wrapper
    raise RuntimeError(msg)
RuntimeError: 10 elements of the 10 element gradient array `gradf` are NaN. This often indicates numerical issues. Consider using `dtype=torch.double`.
(thesisvenv) yash.pisat@MBP-YUP-C02ZTE5UMD6T Experiments %      

> 

>

**Comment by nikohansen** [comment]
I don't quite see that we can do much on the COCO side here. You could check the return values of the COCO function as to whether they are finite, using `np.isfinite` and print the value in case they are not. Let us know what you get. You could assign an arbitrary large value as a finite value, but ultimately, the solver would have to deal with this problem in some way or another.
