### ISSUE TITLE
Largescale Testbed not postprocessible

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1247]
In its current `devel-LS` version, the postprocessing crashes when dealing with data from the `bbob-largescale` experiments. The reason is most likely the absence of a correct reference algorithm with data in dimension 80+:

```
Scaling figures...
  Loading best algorithm data from bestalgentries2009.pickle.gz ...
  done (Thu Dec 08 11:06:59 2016).
Generating LaTeX tables...
  done (Thu Dec 08 11:06:59 2016).
ECDF graphs...
  done (Thu Dec 08 11:07:10 2016).
ECDF graphs per function...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.1
1140-py2.7.egg\bbob_pproc\__main__.py", line 377, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.1
1140-py2.7.egg\bbob_pproc\rungeneric.py", line 270, in main
    + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.1
1140-py2.7.egg\bbob_pproc\rungeneric1.py", line 420, in main
    genericsettings.single_algorithm_file_name)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.1
1140-py2.7.egg\bbob_pproc\compall\pprldmany.py", line 526, in all_single_functio
ns
    next_html_page_suffix='_%02dD' % next_dim)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.1
1140-py2.7.egg\bbob_pproc\compall\pprldmany.py", line 688, in main
    bestalgentry = bestalgentries[(dim, f)]
KeyError: (80, 1)
```
Solution: The fix in the `feature-refalg` branch to deal with non-existing reference algorithms should be integrated also into the `devel-LS` branch.

**Comment by oaelhara** [comment]
It does seem to work. 
Also, there are so many changes in the `feature-refalg` branch in comparison to the current state of the post-processing code in `devel-LS` that I think it makes more sens to simply use that code and adjust it to be large-scale compatible (dimensions of interest...)

**Comment by brockho** [comment]
For me, the postprocessing in the `devel-LS` branch still does not run:

```
C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\build\c\exdata>pytho
n -m bbob_pproc RS_on_bbob-largescale-008

Post-processing: will generate output data in folder ppdata
  this might take several minutes.

Post-processing (1): will generate output data in folder ppdata\RS_on_bbob-largescale-008
  this might take several minutes.
C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\bbob_ppr
oc\pproc.py:857: UserWarning: There is a difference between the maxevals in the *.info file and in t
he data files.
  warnings.warn('There is a difference between the maxevals in the '
C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\bbob_ppr
oc\pproc.py:960: UserWarning:   less than 15 instances in [1, 2, 3, 4, 5, 6, 7] (f5, 80D)
  str(self.dim) + 'D)')
Scaling figures...
  Loading best algorithm data from bestalgentries2016LS.pickle ...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\__main__.py", line 377, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\rungeneric.py", line 270, in main
    + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\rungeneric1.py", line 355, in main
    ppfigdim.main(dsList, values_of_interest, outputdir, genericsettings.verbose)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\ppfigdim.py", line 631, in main
    plot_previous_algorithms(func, _valuesOfInterest)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\ppfigdim.py", line 525, in plot_previous_algorithms
    bestalgentries = bestalg.load_best_algorithm()
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1.2.1.3234-py2.7.egg\
bbob_pproc\bestalg.py", line 363, in load_best_algorithm
    fid = open(pickleFilename, 'r')
IOError: [Errno 2] No such file or directory: 'C:\\Users\\dimo\\AppData\\Roaming\\Python\\Python27\\
site-packages\\bbob_pproc-1.2.1.3234-py2.7.egg\\bbob_pproc\\bestalgentries2016LS.pickle'
```

**Comment by brockho** [comment]
The code in the current `devel-LS` branch of @oaelhara's fork works now such that I'll close this issue.
