### ISSUE TITLE
Restriction of instances not working anymore

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1271]
In the `feature-refalg` branch, the restriction of instances via the `testbedsetting` does not work anymore: when enabling line 315, i.e., when selecting only the first five instances, I get the following error when postprocessing any biobjective data set:
```
Scaling figures...
Loading best algorithm data from refalgs/best2016-bbob-biobj-v2.0.tar.gz ...
    archive extracted to folder C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0
.0.0-py2.7.egg\cocopp\refalgs\_extracted_best2016-bbob-biobj-v2.0 ...
  using: C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\r
efalgs/best2016-bbob-biobj-v2.0.tar.gz
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\__
main__.py", line 373, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\ru
ngeneric.py", line 271, in main
    + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\ru
ngeneric1.py", line 356, in main
    ppfigdim.main(dsList, values_of_interest, algoutputdir)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\pp
figdim.py", line 580, in main
    plot_previous_algorithms(func, _valuesOfInterest)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\pp
figdim.py", line 479, in plot_previous_algorithms
    bestalgentries = bestalg.load_reference_algorithm(testbed.reference_algorithm_filename)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-0.0.0-py2.7.egg\cocopp\be
stalg.py", line 436, in load_reference_algorithm
    bestAlgorithmEntries = generate(dictAlg, dsList[0].algId, dsList[0].instancenumbers)
IndexError: list index out of range
```
The problem is that `dsList` equals `[]` in this case. The same problem occurs for postprocessing `bbob` data sets when the instances are changed but the reference algorithm stays as specified in the repository's `testbedsettings.py`. Only when also changing the reference set to the outdated 'bestalgentries2009.pickle.gz' does the error go away. This indicates that something is wrong with the current reference algorithms or in the way they are read in. Note that both the reference algorithms in the repository and a freshly created one result in the same error message.

**Comment by dtusar** [comment]
This is now fixed on the `feature-refalg` branch.
