### ISSUE TITLE
Error during post-processing with Numpy v1.12

### ISSUE THREAD

**Issue by araffin** [numbbo/coco#1297]
Running post processing on data from ES-SP algorithm (https://github.com/araffin/es-with-search-path) gives an error with **numpy v1.12**:

```
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/comp2/ppfig2.py", line 240, in annotate
    ystars = [annotcoord[1]] * nbstars
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

The reason is that nbstarts is a float (here it is equal to 4.0). This was only giving a warning with a previous version of numpy.

**One solution** is to edit **ppfig2.py** (line 232) :

`        nbstars = np.min([5, -np.ceil(np.log10(nbtests * p + 1e-99))]).astype(int)`

instead of :

`        nbstars = np.min([5, -np.ceil(np.log10(nbtests * p + 1e-99))])`

**Another solution**:
Add this line after the if nbstars > 0 statement :
`nbstars = int(nbstars)`

full error stack:
```
log aRT1/aRT0 vs target function values...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/__main__.py", line 341, in <module>
    rungeneric.main(args)
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/rungeneric.py", line 274, in main
    rungeneric2.main(genopts + ["-o", outputdir] + args)
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/rungeneric2.py", line 419, in main
    outputdir, genericsettings.verbose)
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/comp2/ppfig2.py", line 348, in main
    annotate(entry0, entry1, dim, minfvalue, nbtests=nbtests)
  File "/home/username/.local/lib/python2.7/site-packages/bbob_pproc-1.2-py2.7.egg/bbob_pproc/comp2/ppfig2.py", line 239, in annotate
    ystars = [annotcoord[1]] * nbstars
TypeError: 'numpy.float64' object cannot be interpreted as an index

```

**Comment by brockho** [comment]
Many thanks for reporting this bug and even more for your two suggestions how to fix it. We will have a look into it asap and will include it in the next possible release.

**Comment by brockho** [comment]
I could reproduce the error with numpy 1.12.1 and put the suggested fix in the `development` branch such that the issue can be closed. Many thanks again to @araffin for finding the bug.
