### ISSUE TITLE
Error when using post-processing for many algorithms

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#1327]
Hi all, just a report: when using post-processing for many algorithms on `bbob` testsuite, I encoutered the following error: 
``
C:\Users\Duc  Manh NGUYEN\Desktop\COCO\coco>python -m cocopp --omit-single CMAES-POPSIZE-ADAPT1 IPOP-SEP-CMA-ES BIPOP-CMA-ES AMALGAM

Post-processing (3+): will generate output data in folder ppdata
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\CMAES-POPSIZE-ADAPT1
C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\pproc.py:963: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\IPOP-SEP-CMA-ES
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\BIPOP-CMA-ES
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\AMALGAM
Generating convergence plots...
  done (Thu Mar 09 12:51:10 2017).
ECDF graphs per noise group...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\refalgs/best2009-bbob.tar.gz
  done (Thu Mar 09 12:51:26 2017).
Traceback (most recent call last):
  File "C:\Anaconda2\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\__main__.py", line 373, in <module>
    rungeneric.main(args)
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\rungeneric.py", line 276, in main
    rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\rungenericmany.py", line 366, in main
    inset
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\rungenericmany.py", line 75, in grouped_ecdf_graphs
    settings=settings
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\compall\pprldmany.py", line 665, in main
    bestalgevals = bestalgentry.detEvals(target_values((f, dim)))
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0-py2.7.egg\cocopp\bestalg.py", line 343, in detEvals
    tmp3 = [0, self.success_ratio[i][1]]
IndexError: list index out of range
"

**Comment by brockho** [comment]
Hi @NDManh,

I tried to reproduce the error but could not - neither with the current development branch nor with the coco-2.0 release but I also did not use the exact same four algorithms you used (because your first one is not available online yet I guess). However, I remember that the bestalgs were indeed not working at some point.  It will be therefore nice if you can quickly check whether the code in the current development branch produces the same error and if not, I will make a release later today. Thanks in advance.

**Comment by dtusar** [comment]
Hi, I managed to reproduce the error on the development branch and I will fix it asap.

**Comment by NDManh** [comment]
Hi Dimo, the error occurs also on development branch with three algorithms as below. And just for information: when I tried to turn off the commands `tmp3 = [0, self.success_ratio[i][1]]` in lines 343 and 348 of the file `bestalg.py`, it ran but I don't understand why. 
``
C:\Users\Duc Manh NGUYEN\Desktop\COCO\Development\coco>python -m cocopp --omit-single IPOP-SEP-CMA-ES BIPOP-CMA-ES AMALGAM

Post-processing (3+): will generate output data in folder ppdata
  this might take several minutes.
C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\pproc.py:960: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\IPOP-SEP-CMA-ES
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\BIPOP-CMA-ES
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\AMALGAM
Generating convergence plots...
  done (Thu Mar 09 17:01:12 2017).
ECDF graphs per noise group...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\refalgs\_extracted_best2009-bbob ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\refalgs/best2009-bbob.tar.gz
  done (Thu Mar 09 17:01:22 2017).
Traceback (most recent call last):
  File "C:\Anaconda2\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\__main__.py", line 373, in <module>
    rungeneric.main(args)
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\rungeneric.py", line 277, in main
    rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\rungenericmany.py", line 366, in main
    inset
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\rungenericmany.py", line 75, in grouped_ecdf_graphs
    settings=settings
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\compall\pprldmany.py", line 665, in main
    refalgevals = refalgentry.detEvals(target_values((f, dim)))
  File "C:\Users\Duc Manh NGUYEN\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.41-py2.7.egg\cocopp\bestalg.py", line 347, in detEvals
    tmp3 = [0, self.success_ratio[i][1]]
IndexError: list index out of range
``

**Comment by dtusar** [comment]
The fix is on the development branch. @NDManh can you please check if works for you now.

**Comment by NDManh** [comment]
Hi @dtusar, it works well now. Thanks.
