### ISSUE TITLE
solve conflicts when merging phrsampaio-master-testmerge

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1344]
We currently cannot merge anymore our `phrsampaio-master-testmerge` branch into `development` (nor the other way around).

**Comment by brockho** [comment]
The `development` branch can now be merged again into `phrsampaio-master-testmerge` and vice versa. However, `do.py test-suites` still crashes on the Mac and Windows slaves:
```
PYTHON	test_suites.py 2 in code-experiments/test/regression-test
ERROR: return value=1
using file data\regression_test_2data_for_suite_bbob.py with 4320 test cases done in 2.1s
using file data\regression_test_2data_for_suite_bbob-biobj.py with 9897 test cases done in 11.5s
using file data\regression_test_2data_for_suite_bbob-biobj-ext.py with 16560 test cases bbob_f015_i02_d20__bbob_f019_i04_d20 f,x = (6705, (-0.1285388067798796, 1.6820611389276499, 2.2824817590414, 1.754242740234096, -0.49283013464090497, 1.6380017058035372, 0.4250164627344129, 1.6864886404105537, -2.634249925817251, 3.0554473978739938, -2.9188960416023924, -0.9959672917550455, 0.3033939651035725, -1.3148270633223553, -5.4385116631612505, -0.44247182247591677, -1.2302234539293755, -5.8813237114777746, 1.2966877308054665, -0.502962530203371)) stored x,f,con = ([2511.8966059901513, -0.5001824492091842], []) computed f = [  2.51189661e+03  -5.00182448e-01]
Traceback (most recent call last):
  File "test_suites.py", line 92, in <module>
    "regression_test_%ddata_for_suite_" % ndata + name + ".py"))
  File "test_suites.py", line 62, in regression_test_a_suite
    assert is_equal(f(x), xfc_dict[key][0])
AssertionError
```
What is interesting is that `do.py test-suites` crashes on the `bbob-biobj-ext` suite which runs through in the `development` branch.

**Comment by brockho** [comment]
A slight increase of the equality condition in line 23 of `test_suites.py` from `1e-9` to `2e-9` was necessary to pass the test again. The reason for the test to pass in `development` but not in `phrsampaio-master-testmerge` have been indeed different versions of the `regression_test_2data_for_suite_bbob-constrained.py` file as we had expected in a discussion with @asmaatamna, @dtusar, @ttusar, and @nikohansen.

The `phrsampaio-master-testmerge` branch is now ready to be merged with the `development` branch and I therefore close the issue.
