### ISSUE TITLE
Crash on Windows when installing postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1373]
Since yesterday, I have a strange problem with my Anaconda installation and the `do.py install-postprocessing` crashes with the following error:

```
C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python do.py install-preprocessing
EXPAND  code-preprocessing/archive-update\setup.py.in to code-preprocessing/archive-update\setup.py
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiment
s/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.
c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.
c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testca
ses.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testc
ases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments\build\python
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiment
s/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.
c'] -> code-preprocessing/archive-update/interface/coco.c
EXPAND  code-preprocessing/archive-update/interface/coco.c.in to code-preprocessing/archive-update/i
nterface/coco.c
EXPAND  code-experiments/src/coco.h to code-preprocessing/archive-update/interface/coco.h
PYTHON  setup.py install --user in code-preprocessing/archive-update

C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python do.py build-python
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiment
s/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.
c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.
c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testca
ses.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testc
ases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments\build\python

C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python do.py install-preprocessing
EXPAND  code-preprocessing/archive-update\setup.py.in to code-preprocessing/archive-update\setup.py
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiment
s/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.
c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.
c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testca
ses.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testc
ases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments\build\python
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiment
s/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.
c'] -> code-preprocessing/archive-update/interface/coco.c
EXPAND  code-preprocessing/archive-update/interface/coco.c.in to code-preprocessing/archive-update/i
nterface/coco.c
EXPAND  code-experiments/src/coco.h to code-preprocessing/archive-update/interface/coco.h
PYTHON  setup.py install --user in code-preprocessing/archive-update

C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python do.py install-postprocessing
EXPAND  code-postprocessing\setup.py.in to code-postprocessing\setup.py
PYTHON  setup.py install --user in code-postprocessing
ERROR: return value=1
running install
running bdist_egg
running egg_info
writing cocopp.egg-info\PKG-INFO
writing top-level names to cocopp.egg-info\top_level.txt
writing dependency_links to cocopp.egg-info\dependency_links.txt
reading manifest file 'cocopp.egg-info\SOURCES.txt'
writing manifest file 'cocopp.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying cocopp.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying cocopp.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying cocopp.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying cocopp.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
cocopp.bestalg: module references __file__
cocopp.htmldesc: module references __file__
cocopp.ppfig: module references __file__
cocopp.pprldistr: module references __file__
cocopp.pproc: module references __file__
cocopp.preparehtml: module references __file__
cocopp.testbedsettings: module references __file__
cocopp.__main__: module references __file__
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    'Topic :: ??'
  File "C:\Users\dimo\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\dimo\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\dimo\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\install.py", line 109, in do_eg
g_install
    self.run_command('bdist_egg')
  File "C:\Users\dimo\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\dimo\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 209, in run

    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 245, in zip
_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 355, in ana
lyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "C:\Users\dimo\Anaconda2\lib\site-packages\setuptools\command\bdist_egg.py", line 392, in sca
n_module
    code = marshal.load(f)
EOFError: EOF read where object expected

Traceback (most recent call last):
  File "do.py", line 966, in <module>
    main(sys.argv[1:])
  File "do.py", line 934, in main
    elif cmd == 'install-postprocessing': install_postprocessing()
  File "do.py", line 246, in install_postprocessing
    python('code-postprocessing', ['setup.py', 'install', '--user'], verbose=_verbosity)
  File "C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\tools\cocout
ils.py", line 144, in python
    universal_newlines=True)
  File "C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\tools\cocout
ils.py", line 42, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "C:\Users\dimo\Anaconda2\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Users\\dimo\\Anaconda2\\python.exe', 'setup.py', 'inst
all', '--user']' returned non-zero exit status 1
```

Rebooting my Windows did not help and also a fresh Anaconda installation did not help. What is interesting is that both `do.py install-preprocessing` and `do.py build-python` work.

**Comment by brockho** [comment]
Okay, according to
```
http://stackoverflow.com/questions/37814654/python-setuptools-bad-marshal-data
```
the trick was to add a `zip_safe=False` into the `setup.py.in` of the `code-postprocessing/` folder, to be more precise for example at the bottom as
```
[...]
    classifiers = [
        'Development Status :: 4 - Beta',
        'Environment :: ??',
        'Intended Audience :: ??',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: ??'
    ],
    zip_safe=False
)
``` 
Running `python do.py install-postprocessing` was then working again.
