### ISSUE TITLE
do.py test-postprocessing fails

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1391]
I believe I have seen this before, but we really should solve it to be able to run a decent test again.
```
[15:29:57] 0 coco$ ./do.py test-postprocessing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install --user in code-postprocessing
PYTHON	test.py in code-postprocessing/cocopp
ERROR: return value=1
Using grayscale settings.

Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to consistency_check() in pproc.DataSet
Generating convergence plots...
  done (Fri May 26 15:31:32 2017).
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder /Users/hansen/.local/lib/python2.7/site-packages/cocopp-2.0.288-py2.7.egg/cocopp/refalgs/_extracted_best2009-bbob ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: /Users/hansen/.local/lib/python2.7/site-packages/cocopp-2.0.288-py2.7.egg/cocopp/refalgs/best2009-bbob.tar.gz
  done (Fri May 26 15:31:34 2017).
  done (Fri May 26 15:31:51 2017).
Generating LaTeX tables...
  done (Fri May 26 15:31:51 2017).
ECDF graphs...
  done (Fri May 26 15:32:03 2017).
ECDF graphs per function...
  done (Fri May 26 15:32:27 2017).
aRT loss ratio figures and tables...
  done (Fri May 26 15:32:32 2017).
Output data written to folder ppdata
  done (Fri May 26 15:32:32 2017).
preparing algorithm data
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale --conv /Users/hansen/git/coco/code-postprocessing/cocopp/data/BFGS_ros_noiseless.tgz
**  subtest 1 finished in  85.0064730644  seconds
Traceback (most recent call last):
  File "test.py", line 342, in <module>
    main(args)
  File "test.py", line 180, in main
    run_latex_template("templateBBOBarticle.tex")
  File "test.py", line 58, in run_latex_template
    assert not result, 'Test failed: error while running bibtex on %s.' % os.path.splitext(filename)[0]
AssertionError: Test failed: error while running bibtex on templateBBOBarticle.

Traceback (most recent call last):
  File "./do.py", line 966, in <module>
    main(sys.argv[1:])
  File "./do.py", line 954, in main
    elif cmd == 'test-postprocessing': test_postprocessing()
  File "./do.py", line 745, in test_postprocessing
    python('code-postprocessing/cocopp', ['test.py'], verbose=_verbosity)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 144, in python
    universal_newlines=True)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 42, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "/Users/hansen/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/hansen/anaconda/bin/python', 'test.py']' returned non-zero exit status 1
[15:32:33] 0 coco$ 
```

**Comment by dtusar** [comment]
This should be solved now. You can check the latest comment in #1002.

**Comment by nikohansen** [comment]
Still not solved, or a new error: 
```
[20:51:43] 1 coco$ git co dev
Switched to branch 'dev'
Your branch is up-to-date with 'coco/development'.
[20:51:48] 1 coco$ git pull --rebase
Current branch dev is up to date.
[20:51:58] 1 coco$ ./do.py test-postprocessing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install --user in code-postprocessing
PYTHON	test.py in code-postprocessing/cocopp
ERROR: return value=1
Using grayscale settings.

Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to consistency_check() in pproc.DataSet
Generating convergence plots...
  done (Tue Jun 13 20:52:39 2017).
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder /Users/hansen/.local/lib/python2.7/site-packages/cocopp-2.0.359-py2.7.egg/cocopp/refalgs/.extracted_best2009-bbob ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: /Users/hansen/.local/lib/python2.7/site-packages/cocopp-2.0.359-py2.7.egg/cocopp/refalgs/best2009-bbob.tar.gz
  done (Tue Jun 13 20:52:40 2017).
  done (Tue Jun 13 20:52:56 2017).
Generating LaTeX tables...
  done (Tue Jun 13 20:52:57 2017).
ECDF graphs...
  done (Tue Jun 13 20:53:08 2017).
ECDF graphs per function...
  done (Tue Jun 13 20:53:32 2017).
aRT loss ratio figures and tables...
  done (Tue Jun 13 20:53:37 2017).
Output data written to folder ppdata
  done (Tue Jun 13 20:53:37 2017).
preparing algorithm data
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale --conv /Users/hansen/git/coco/code-postprocessing/cocopp/data/BFGS_ros_noiseless.tgz
**  subtest 1 finished in  83.8913459778  seconds
Traceback (most recent call last):
  File "test.py", line 338, in <module>
    main(args)
  File "test.py", line 180, in main
    run_latex_template("templateBBOBarticle.tex")
  File "test.py", line 58, in run_latex_template
    assert not result, 'Test failed: error while running bibtex on %s.' % os.path.splitext(filename)[0]
AssertionError: Test failed: error while running bibtex on templateBBOBarticle.

Traceback (most recent call last):
  File "./do.py", line 966, in <module>
    main(sys.argv[1:])
  File "./do.py", line 954, in main
    elif cmd == 'test-postprocessing': test_postprocessing()
  File "./do.py", line 745, in test_postprocessing
    python('code-postprocessing/cocopp', ['test.py'], verbose=_verbosity)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 144, in python
    universal_newlines=True)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 42, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "/Users/hansen/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/hansen/anaconda/bin/python', 'test.py']' returned non-zero exit status 1
```

**Comment by brockho** [comment]
@nikohansen: did you try the suggestion of the last comment of #1002 as mentioned by Dejan? This solved the issue on our CI Mac slave but maybe you have another Mac OS version than this one and we have to find another fix.

**Comment by nikohansen** [comment]
Re " _The `ACM-Reference-Format.bst` file of the GECCO ACM style was not included in the TeXLive distribution_ ", how do I fix this?

**Comment by nikohansen** [comment]
On a more general point, what is the reason we want to run bibtex to test the post-processing? It doesn't seem to make much sense to me, as we could just provide the necessary .bbl file.

**Comment by brockho** [comment]
> Re " The ACM-Reference-Format.bst file of the GECCO ACM style was not included in the TeXLive distribution ", how do I fix this?

@nikohansen: the file should now be inside our Coco repository.

> On a more general point, what is the reason we wanted to run bibtex to test the post-processing? It doesn't seem to make much sense to me, as we could just provide the necessary .bbl file if we wanted to test the generated LaTeX output.

I agree. But then we will have to make sure that the `.bbl` file is always up-to-date when we change the `bbob.bib` file (which was changed 9 times so far since February 2016). In addition, it might be more confusing for the enduser to add their own references if we just `\input` the `.bbl` file by default. I therefore opt to leave the `bibtex` within the test for the moment.

**Comment by nikohansen** [comment]
I believe if a reference is not included in the `.bbl` file, we get an error anyway, so this shouldn't be a concern. AFAICS, the `.bbl` should not be part of the distribution itself but part of the testing code, so that shouldn't lead to confusion.

**Comment by nikohansen** [comment]
Test still doesn't work for me.

**Comment by brockho** [comment]
decision of June 20: move the bibtex test simply to the nightly build

**Comment by dtusar** [comment]
Bibtex moved. @nikohansen please try if the `test-postprocessing` works for you now.

**Comment by nikohansen** [comment]
Looks fine now, thanks: 
```
[20:55:04] 0 coco$ ./do.py test-postprocessing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install --user in code-postprocessing
PYTHON	test.py in code-postprocessing/cocopp
PYTHON	generate_aRTA_plot.py in code-postprocessing/aRTAplots
[21:06:14] 0 coco$ 
```
