### ISSUE TITLE
examining output while the post-processing is running

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1414]
Currently to complete the post-processing may take only a few second, but may also take 10 or 20 minutes. We should attempt to make this waiting time more valuable, such that it is able to examen the written output from the time where it is written. That is, the proper index `html` files should be available as soon as possible.

**Comment by dtusar** [comment]
The `html` files are now created as soon as we start getting the corresponding plots.

**Comment by brockho** [comment]
This issue is not solved, it seems:

```
C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\build\python\exdata>
python -m cocopp -o ppdatacma fmin_on_bbob_budget20000xD
Post-processing (1)
  Using:
    .\fmin_on_bbob_budget20000xD

Post-processing (1)
C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\pproc.py:1302: UserWarning
: logger is an additional attribute.
  warnings.warn('%s is an additional attribute.' % (attrname))
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\__main__.py", line
 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\rungeneric.py", li
ne 279, in main
    dsld = rungeneric1.main(genopts + ["-o", outputdir, alg])
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\rungeneric1.py", l
ine 274, in main
    dsList = DataSetList(filelist)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\pproc.py", line 16
89, in __init__
    self.processIndexFile(name)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\pproc.py", line 17
60, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\pproc.py", line 90
4, in __init__
    datasets, algorithms, reference_values, success_ratio = split(dataFiles, idx_to_load=idx_of_inst
ances_to_load)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.0.672-py2.7.egg\cocopp\readalign.py", lin
e 487, in split
    if (idx_to_load is None) or (idx_to_load and idx_to_load[idx]):
IndexError: list index out of range

C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\build\python\exdata>
```

Note that the problem only occurs when an algorithm needs sufficiently long time for a single instance such as the above CMA-ES or DFO-TR. Running a short randomsearch experiment with `example_experiment.py` might allow for looking at a still running experiment (that worked for me on Friday).

I guess that the problem appears with unfinished `.info` files that don't have the expected format.

**Comment by nikohansen** [comment]
Wrong issue, I think this should reopen rather #1411.
