### ISSUE TITLE
Wrong links in postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1452]
When postprocessing an algorithm data set that is not directly located in the folder where the postprocessing is started (e.g. `2017/SMS-EMOA-SA.tgz`), some of the links in the HTML are broken.

For the above example (one algorithm in `2017/SMS-EMOA-SA.tgz` postprocessing), for example, the HTML links to `2017/2017/pprldmany_02D_noiselessall.svg` within `2017/pprldmany.html` although the plot is located in `2017/pprldmany_02D_noiselessall.svg`, see the tooltip here:

![image](https://user-images.githubusercontent.com/13706996/28059387-66ef1486-6624-11e7-8b59-a844629477e9.png)

**Comment by brockho** [comment]
@dtusar: With the current code (development branch), the above even breaks now and produces no output whatsoever:
```
C:\Users\dimo\Desktop\numbbo\personal-workspaces\dimo\allBBOBalgopaper\2016-biobj>python -m cocopp -
o ppdata-TestDejan DEMO.tgz 2017/SMS-EMOA-DE.tgz

Post-processing (2+)
    archive extracted to folder .\.extracted_DEMO ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: .\DEMO.tgz
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
rungeneric.py", line 268, in main
    dsld = rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
rungenericmany.py", line 283, in main
    dsList, sortedAlgs, dictAlg = processInputArgs(args, True)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
pproc.py", line 2629, in processInputArgs
    process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
pproc.py", line 2646, in process_arguments
    filelist = findfiles.main(i)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
findfiles.py", line 46, in main
    directory = get_directory(directory, True)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.558-py2.7.egg\cocopp\
findfiles.py", line 100, in get_directory
    tar_file = tarfile.TarFile.open(directory)
  File "C:\Users\dimo\Anaconda2\lib\tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\dimo\Anaconda2\lib\tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "C:\Users\dimo\Anaconda2\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '.\\2017/SMS-EMOA-DE.tgz'
```

`DEMO.tgz` is extracted correctly, `2017/SMS-EMOA-DE.tgz` is not. This definitely worked at some point and shall be fixed asap.

**Comment by nikohansen** [comment]
Is it a problem with the path separator?

**Comment by dtusar** [comment]
I'm not sure, for me it works either way (with slash or backslash).

**Comment by nikohansen** [comment]
Shouldn't we _always_ use `os.sep` or `os.path.join` and something like `os.path.join(*my_filename.split('/'))` (caveat: this doesn't work for absolution paths) just be sure to never run into a separator problem?

**Comment by brockho** [comment]
The last error was not really an error, it seems: I simply used the wrong filename. With the right filename, I cannot reproduce the error - still the folders are messed up but @dtusar found already the fix in the meantime.

**Comment by brockho** [comment]
Commit e004a88 now solved this issue. Thanks to @dtusar for the suggested code.
