### ISSUE TITLE
do.py run-octave and exampleexperiment.m fails on MacOS

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1453]
While `build-octave` works, `run-octave` gives this error: 
```
[15:27:16] 0 coco$ ./do.py run-octave
CLEAN	mex files from code-experiments/build/matlab/
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/matlab/coco.c
EXPAND	code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
WRITE	code-experiments/build/matlab/REVISION
WRITE	code-experiments/build/matlab/VERSION
RUN	octave --no-gui setup.m in code-experiments/build/matlab
RUN	octave --no-gui exampleexperiment.m in code-experiments/build/matlab
ERROR: return value=1
GNU Octave, version 3.8.0
Copyright (C) 2013 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin13.0.0".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

error: invalid use of script /Users/hansen/git/coco/code-experiments/build/matlab/cocoCall.m in index expression
error: called from:
error:   /Users/hansen/git/coco/code-experiments/build/matlab/cocoSuite.m at line 43, column 7
error:   /Users/hansen/git/coco/code-experiments/build/matlab/exampleexperiment.m at line 47, column 7

Traceback (most recent call last):
  File "./do.py", line 960, in <module>
    main(sys.argv[1:])
  File "./do.py", line 933, in main
    elif cmd == 'run-octave': run_octave()
  File "./do.py", line 534, in run_octave
    ['octave', '--no-gui', 'exampleexperiment.m'], verbose=_verbosity)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 120, in run
    universal_newlines=True)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 42, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "/Users/hansen/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['octave', '--no-gui', 'exampleexperiment.m']' returned non-zero exit status 1
```
`test-octave` gives:

```
[15:30:40] 0 coco$ ./do.py test-octave
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/matlab/coco.c
EXPAND	code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
WRITE	code-experiments/build/matlab/REVISION
WRITE	code-experiments/build/matlab/VERSION
RUN	octave --no-gui setup.m in code-experiments/build/matlab
RUN	octave --no-gui exampleexperiment.m in code-experiments/build/matlab
ERROR: return value=1
GNU Octave, version 3.8.0
Copyright (C) 2013 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin13.0.0".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

error: invalid use of script /Users/hansen/git/coco/code-experiments/build/matlab/cocoCall.m in index expression
error: called from:
error:   /Users/hansen/git/coco/code-experiments/build/matlab/cocoSuite.m at line 43, column 7
error:   /Users/hansen/git/coco/code-experiments/build/matlab/exampleexperiment.m at line 47, column 7
```
The same problem when running `exampleexperiment.m` in Octave.

**Comment by nikohansen** [comment]
It works under octave version 4.2.1, so I will close this as won't fix.
