### ISSUE TITLE
python -m cocopp.test fails (breaking circleci)

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1523]
The python 2 test on circleci [fails](https://circleci.com/gh/numbbo/coco/298) since a few days (it was OK before). I get the same error on my Mac when invoking `python -m cocopp.test` from the `code-postprocessing` folder. The test bails out when doctest is run. 

```
[...]
ALL done (Thu Aug 31 14:14:44 2017).
**  subtest 2 finished in  164.675256968  seconds
launching doctest (it might be necessary to close a few pop up windows to finish)
cocopp/pproc.py:2728: UserWarning: No data for algorithm data/MCS.tgz in 40-D.
  warnings.warn(txt)
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f1 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f2 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f3 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f4 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f5 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f6 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f7 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f8 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f9 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f10 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f11 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f12 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f13 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f14 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f15 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f16 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f17 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f18 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f19 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f20 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f21 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f22 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f23 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f24 40-D.
  % (alg, f, d))
cocopp/pproc.py:1084: UserWarning:   less than 15 instances in [0] (f1, 40D)
  str(self.dim) + 'D)')
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 209, in pproc.py
Failed example:
    bb.config.config('GECCOBBOBTestbed')
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[9]>", line 1, in <module>
        bb.config.config('GECCOBBOBTestbed')
    AttributeError: 'module' object has no attribute 'config'
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 214, in pproc.py
Failed example:
    targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[12]>", line 1, in <module>
        targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
      File "cocopp/pproc.py", line 349, in __call__
        self.initialize()
      File "cocopp/pproc.py", line 303, in initialize
        self.reference_data = bestalg.load_reference_algorithm(self.reference_algorithm, force=True)
      File "cocopp/bestalg.py", line 439, in load_reference_algorithm
        dsList, sortedAlgs, dictAlg = pproc.processInputArgs(algList)
      File "cocopp/pproc.py", line 2629, in processInputArgs
        process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
      File "cocopp/pproc.py", line 2646, in process_arguments
        filelist = findfiles.main(i)
      File "cocopp/findfiles.py", line 42, in main
        directory = get_directory(directory, True)
      File "cocopp/findfiles.py", line 77, in get_directory
        tar_file = tarfile.TarFile.open(directory)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1675, in open
        return func(name, "r", fileobj, **kwargs)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1740, in gzopen
        fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
      File "/Users/hansen/anaconda/lib/python2.7/gzip.py", line 94, in __init__
        fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
    IOError: [Errno 2] No such file or directory: 'cocopp/refalgs/best2009-bbob.tar.gz'
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 720, in pproc.py
Failed example:
    bb.config.config('GECCOBBOBTestbed') # make sure that settings are used
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[52]>", line 1, in <module>
        bb.config.config('GECCOBBOBTestbed') # make sure that settings are used
    AttributeError: 'module' object has no attribute 'config'
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 723, in pproc.py
Failed example:
    dslist2[2].instancenumbers
Expected:
    [1, 1, 1, 3, 3, 3]
Got:
    [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 725, in pproc.py
Failed example:
    dslist2[2].evals[-1]
Expected:
    array([  1.00000000e-08,   2.14200000e+03,   1.95800000e+03,
             2.31700000e+03,   2.32400000e+03,   2.30500000e+03,
             2.20700000e+03])
Got:
    array([  1.00000000e-08,   2.14200000e+03,   1.95800000e+03,
             2.31700000e+03,   2.22700000e+03,   2.26900000e+03,
             2.09000000e+03,   2.32400000e+03,   2.30500000e+03,
             2.20700000e+03,   1.96200000e+03,   2.42800000e+03,
             2.21400000e+03,   1.97000000e+03,   1.92400000e+03,
             2.01200000e+03])
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 731, in pproc.py
Failed example:
    bb.config.config('GECCOBBOBTestbed') # make sure that settings are used
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[57]>", line 1, in <module>
        bb.config.config('GECCOBBOBTestbed') # make sure that settings are used
    AttributeError: 'module' object has no attribute 'config'
**********************************************************************
1 items had failures:
   6 of  58 in pproc.py
***Test Failed*** 6 failures.
doctest file "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py" failed
** doctest finished in  28.4900491238  seconds
*** done testing module cocopp ***
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/git/coco/code-postprocessing/cocopp/test.py", line 348, in <module>
    main(args)
  File "/Users/hansen/git/coco/code-postprocessing/cocopp/test.py", line 333, in main
    raise ValueError('%d of %d tests failed' % (failure_count, test_count))
ValueError: 6 of 115 tests failed
```

**Comment by nikohansen** [comment]
The test command on a previous version of the `development` branch, commit 3a9a481f, fails with another error but I believe in the same `cocopp` call: 
```
ALL done (Thu Aug 31 15:11:02 2017).
**  subtest 2 finished in  173.355419874  seconds
launching doctest (it might be necessary to close a few pop up windows to finish)
cocopp/pproc.py:2728: UserWarning: No data for algorithm data/MCS.tgz in 40-D.
  warnings.warn(txt)
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f1 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f2 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f3 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f4 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f5 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f6 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f7 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f8 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f9 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f10 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f11 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f12 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f13 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f14 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f15 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f16 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f17 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f18 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f19 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f20 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f21 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f22 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f23 40-D.
  % (alg, f, d))
cocopp/bestalg.py:133: UserWarning: Algorithm data/MCS.tgz was not tested on f24 40-D.
  % (alg, f, d))
cocopp/pproc.py:1084: UserWarning:   less than 15 instances in [0] (f1, 40D)
  str(self.dim) + 'D)')
**********************************************************************
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 214, in pproc.py
Failed example:
    targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[12]>", line 1, in <module>
        targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
      File "cocopp/pproc.py", line 349, in __call__
        self.initialize()
      File "cocopp/pproc.py", line 303, in initialize
        self.reference_data = bestalg.load_reference_algorithm(self.reference_algorithm, force=True)
      File "cocopp/bestalg.py", line 439, in load_reference_algorithm
        dsList, sortedAlgs, dictAlg = pproc.processInputArgs(algList)
      File "cocopp/pproc.py", line 2629, in processInputArgs
        process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
      File "cocopp/pproc.py", line 2646, in process_arguments
        filelist = findfiles.main(i)
      File "cocopp/findfiles.py", line 42, in main
        directory = get_directory(directory, True)
      File "cocopp/findfiles.py", line 77, in get_directory
        tar_file = tarfile.TarFile.open(directory)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1675, in open
        return func(name, "r", fileobj, **kwargs)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1740, in gzopen
        fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
      File "/Users/hansen/anaconda/lib/python2.7/gzip.py", line 94, in __init__
        fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
    IOError: [Errno 2] No such file or directory: 'cocopp/refalgs/best2009-bbob.tar.gz'
**********************************************************************
1 items had failures:
   1 of  58 in pproc.py
***Test Failed*** 1 failures.
doctest file "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py" failed
** doctest finished in  23.6238310337  seconds
*** done testing module cocopp ***
```
This means also that the CI doesn't detect these errors?

**Comment by brockho** [comment]
Where did you run the tests, on your own machine? The `IOError: [Errno 2] No such file or directory: 'cocopp/refalgs/best2009-bbob.tar.gz'` suggests that the error is local and has not been there on the CI slaves. The file `cocopp/refalgs/best2009-bbob.tar.gz` has not changed at all for a while.

Can it be that your `cocopp` installation was/is broken at some point? I remember I had a similar error once where I cancelled the `do.py install-postprocessing` and some files have not been copied correcly to the python folder.

**Comment by nikohansen** [comment]
I am running the test on my machine, but not on an installed module but on the repository itself. 

As mentioned above, we can see the same error [on circleci](https://circleci.com/gh/numbbo/coco), where the Python 2 test went through at some point and now fails with the same error.

**Comment by nikohansen** [comment]
@dtusar , do you have any idea where this problem comes from? Could it be related to copying data in the test preparation?

**Comment by dtusar** [comment]
I uninstalled `cocopp `and called `python -m cocopp.test` in the `code-postprocessing` folder as suggested and I got the same errors. Interestingly, now I get these errors also after installing `cocopp` again or when calling `python do.py test-postprocessing`.

**Comment by brockho** [comment]
Together with @nikohansen, we most likely found the reason for this bug. The first thing is a missing `from . import config` within `__init__.py`. Adding this, another test in `pproc.py` breaks which indicates that the current folder is another than expected---resulting from a directory change in some other doctest. The question is simply where this other test is...

**Comment by dtusar** [comment]
You can find `os.chdir` calls in some doctests. Not sure which one is problematic.

**Comment by nikohansen** [comment]
Any is potentially problematic, unless reverted.

I just wanted to add that even the `config` import error might be the same error, due to a changed working folder. If config is imported before the doctest is started, the error doesn't show up, because it won't be imported again.

**Comment by dtusar** [comment]
@brockho If you can push your changes I will try to solve the test that still fails.

**Comment by nikohansen** [comment]
@brockho FTR, the module property idea didn't work out.

**Comment by nikohansen** [comment]
I can report good news: ``module_relative=True`` instead of ``module_relative=False`` fixes the test locally for me.

**Comment by nikohansen** [comment]
FTR, if I add the line `from . import config` in `__init__.py`, the error for `python -m coco.test` I get is `No such file or directory: 'cocopp/refalgs/best2009-bbob.tar.gz'`: 
```
File "/Users/hansen/git/coco/code-postprocessing/cocopp/pproc.py", line 215, in pproc.py
Failed example:
    targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/Users/hansen/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pproc.py[13]>", line 1, in <module>
        targets(fun_dim=(1, 20)) # doctest:+ELLIPSIS
      File "cocopp/pproc.py", line 350, in __call__
        self.initialize()
      File "cocopp/pproc.py", line 304, in initialize
        self.reference_data = bestalg.load_reference_algorithm(self.reference_algorithm, force=True)
      File "cocopp/bestalg.py", line 439, in load_reference_algorithm
        dsList, sortedAlgs, dictAlg = pproc.processInputArgs(algList)
      File "cocopp/pproc.py", line 2630, in processInputArgs
        process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
      File "cocopp/pproc.py", line 2647, in process_arguments
        filelist = findfiles.main(i)
      File "cocopp/findfiles.py", line 46, in main
        directory = get_directory(directory, True)
      File "cocopp/findfiles.py", line 100, in get_directory
        tar_file = tarfile.TarFile.open(directory)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1675, in open
        return func(name, "r", fileobj, **kwargs)
      File "/Users/hansen/anaconda/lib/python2.7/tarfile.py", line 1740, in gzopen
        fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
      File "/Users/hansen/anaconda/lib/python2.7/gzip.py", line 94, in __init__
        fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
    IOError: [Errno 2] No such file or directory: 'cocopp/refalgs/best2009-bbob.tar.gz'
```
I am not fully convinced that the reason is folder changes in previous doctests.

**Comment by brockho** [comment]
I can report that I get exactly the same than @nikohansen - and changing `module_relative` seems to have no effect either on my Windows machine (tested with Anaconda python 2.7).

**Comment by brockho** [comment]
Maybe good news now from my side: Adding `relative_load=False` to 
```
self.reference_data = bestalg.load_reference_algorithm(self.reference_algorithm, force=True, relative_load=False)
```
in line 303 of `pproc.py` solves the issue for me. The test now runs through both without having the `cocopp` module installed and via `python do.py test-postprocessing`.

Very strange though that we had this issue only recently since both line 303 and the definition of `load_reference_algorithm` in `bestalg.py` have not been touched for the last 11 months...

I will prepare a pull request with this change together with a temporary cleanup of the `os.chdir` in the doctests that should later on this week be replaced by tests without the need to change the directories wherever possible.

**Comment by brockho** [comment]
BTW, `from . import config` in `__init__.py` is needed to fix the issue.

**Comment by nikohansen** [comment]
The fix did fix the test, but broke a normal use-case, see https://github.com/numbbo/coco/pull/1528

**Comment by dtusar** [comment]
Now this should be fixed.
