### ISSUE TITLE
Postprocessing fails on biobjective algorithm data in Python 3

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1548]
The calls
````
python -m cocopp ALG_NAME.tgz
````
and
````
python -m cocopp ALG_NAME
````
fail on Windows with Python 3.6.0 for biobjective optimization algorithms. The error message is as follows:
````
Post-processing (1): will generate output data in folder ppdata\ALG_NAME
  this might take several minutes.
    archive extracted to folder D:\.extracted_ALG_NAME ...
  Data consistent according to consistency_check() in pproc.DataSet
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tea\AppData\Roaming\Python\Python36\site-packages\cocopp-2.0.480-py3.6.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\tea\AppData\Roaming\Python\Python36\site-packages\cocopp-2.0.480-py3.6.egg\cocopp\rungeneric.py", line 261, in main
    dsld = rungeneric1.main(genopts + ["-o", outputdir, alg])
  File "C:\Users\tea\AppData\Roaming\Python\Python36\site-packages\cocopp-2.0.480-py3.6.egg\cocopp\rungeneric1.py", line 280, in main
    store_reference_values(dsList)
  File "C:\Users\tea\AppData\Roaming\Python\Python36\site-packages\cocopp-2.0.480-py3.6.egg\cocopp\pproc.py", line 2687, in store_reference_values
    testbedsettings.update_reference_values(key[0], value.get_reference_values_hash())
  File "C:\Users\tea\AppData\Roaming\Python\Python36\site-packages\cocopp-2.0.480-py3.6.egg\cocopp\pproc.py", line 2494, in get_reference_values_hash
    result = hashlib.sha1(reference_values_string).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
````

It works fine when I switch to Python 2 (more specifically, Python 2.7.13).

I haven't checked if it works for singleobjective algorithms...

EDIT: The same error appears for data in folders and .tgz files.

**Comment by ttusar** [comment]
Fixed by the latest commit to the development branch
