### ISSUE TITLE
Nail in Jenkins' coffin

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1582]
Anybody else also tired of this `IOError: [Errno 28] No space left on device` non-sense?
```
python -m  cocopp --no-svg --settings=grayscale  /builds/disk/workspace/Coco-test3-linux/dotype/test-postprocessing/label/numbbo-ubuntu-12p04-i386/pyversion/python/code-postprocessing/cocopp/data/RS-4.tgz
**  subtest 2 finished in  206.462979078  seconds
launching doctest (it might be necessary to close a few pop up windows to finish)
**********************************************************************
File "/builds/disk/workspace/Coco-test3-linux/dotype/test-postprocessing/label/numbbo-ubuntu-12p04-i386/pyversion/python/code-postprocessing/cocopp/bestalg.py", line 689, in bestalg.py
Failed example:
    bestalg.getAllContributingAlgorithmsToBest(('data/BIPOP-CMA-ES.tgz', 'data/MCS.tgz')) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest bestalg.py[23]>", line 1, in <module>
        bestalg.getAllContributingAlgorithmsToBest(('data/BIPOP-CMA-ES.tgz', 'data/MCS.tgz')) # doctest:+ELLIPSIS
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/bestalg.py", line 696, in getAllContributingAlgorithmsToBest
        custom_generate(algnamelist, algId='bestCustomAlg')
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/bestalg.py", line 545, in custom_generate
        dsList, sortedAlgs, dictAlg = pproc.processInputArgs(args)
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/pproc.py", line 2645, in processInputArgs
        process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/pproc.py", line 2662, in process_arguments
        filelist = findfiles.main(i)
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/findfiles.py", line 51, in main
        directory = get_directory(directory, True)
      File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.644-py2.7.egg/cocopp/findfiles.py", line 111, in get_directory
        tar_file.extractall(dir_name)
      File "/usr/lib/python2.7/tarfile.py", line 2048, in extractall
        self.extract(tarinfo, path)
      File "/usr/lib/python2.7/tarfile.py", line 2085, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "/usr/lib/python2.7/tarfile.py", line 2161, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/usr/lib/python2.7/tarfile.py", line 2201, in makefile
        copyfileobj(source, target)
      File "/usr/lib/python2.7/tarfile.py", line 266, in copyfileobj
        shutil.copyfileobj(src, dst)
      File "/usr/lib/python2.7/shutil.py", line 52, in copyfileobj
        fdst.write(buf)
    IOError: [Errno 28] No space left on device
**********************************************************************
1 items had failures:
   1 of  25 in bestalg.py
***Test Failed*** 1 failures.
doctest file "/builds/disk/workspace/Coco-test3-linux/dotype/test-postprocessing/label/numbbo-ubuntu-12p04-i386/pyversion/python/code-postprocessing/cocopp/bestalg.py" failed
** doctest finished in  27.0846168995  seconds
*** done testing module cocopp ***
Traceback (most recent call last):
  File "test.py", line 355, in <module>
    main(sys.argv[1:])
  File "test.py", line 341, in main
    raise ValueError('%d of %d tests failed' % (failure_count, test_count))
ValueError: 1 of 133 tests failed

Build step 'Execute shell' marked build as failure
Sending e-mails to: dejan.tusar@inria.fr nikohansen@users.noreply.github.com
Finished: FAILURE
```

**Comment by brockho** [comment]
Yes :-) That's why we talked this week about uninstalling the python modules (incl. the downloaded data files) after each test.

**Comment by brockho** [comment]
FYI:
```
ci@numbbo-ubuntu-12p04-i386:~/disk/workspace$ du -hs */
4.6G    Coco-devel-linux/
1.7G    Coco-dev-nightly/
4.4G    Coco-test1-linux/
294M    Coco-test1-win/
4.4G    Coco-test2-linux/
294M    Coco-test2-win/
4.5G    Coco-test3-linux/
295M    Coco-test3-win/
```
and 
```
ci@numbbo-ubuntu-12p04-i386:~/disk/workspace$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1       18625404 15353928   2325352  87% /
udev             6201768        4   6201764   1% /dev
tmpfs            1241812      268   1241544   1% /run
none                5120        0      5120   0% /run/lock
none             6209052        0   6209052   0% /run/shm
/dev/vda       103212320 21303236  76666204  22% /builds/disk
```

Not clear, why we get these "running out of space" messages when only 22% of the disk is used...

**Comment by nikohansen** [comment]
I am trying to rewrite the tests, such that they do not pollute the module installation space anymore.

**Comment by brockho** [comment]
What I did was to restrict the number of builds that are kept in Jenkins (at least on some of the tests/projects). For now, that's enough that all tests can run, but in the long run, we might need to consider uninstalling the installed modules after the tests to save further space.

For now, I suggest to close the issue. What do you think?

**Comment by brockho** [comment]
BTW, the latest change related to how the algorithm data sets are downloaded in the tests, slightly saved some space:
```
ci@numbbo-ubuntu-12p04-i386:~/disk/workspace$ du -hs */
4.3G    Coco-devel-linux/
847M    Coco-dev-nightly/
4.3G    Coco-test1-linux/
293M    Coco-test1-win/
4.3G    Coco-test2-linux/
294M    Coco-test2-win/
4.3G    Coco-test3-linux/
294M    Coco-test3-win/
```
compared to the above. The largest amount of space is saved for the nightly build which makes sense because it uses the most algorithm data sets. [The other smaller folders are likely the ones where only the master thread was running on this machine, but the (Windows) tests happened on another slave.]

**Comment by dtusar** [comment]
With the `data-archive` folder the data files are now downloaded only once and not in each `cocopp` package. This will stabilize the amount of space used by the post processing. Currently the `data-archive` folder uses cca. 1 GB of space on the system disk (with the size of 20 GB) which can increase if we add more algorithms to the tests. 

The example of the saved space above it's nice to see but IMO not too important because the shown folders are on the external disk with the size of 100 GB. There is still plenty of space. The ideal solution would be to write the `data-archive` to this external disk.
