### ISSUE TITLE
delete_files in test.py

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1600]
leads to this error
```
ALL done (Wed Sep 27 23:44:00 2017).
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  76.6953637599945  seconds
python -m  cocopp --no-svg --settings=grayscale RS-4.tgz
**  subtest 2 finished in  152.57823014259338  seconds
Traceback (most recent call last):
  File "test.py", line 389, in <module>
    main(sys.argv[1:])
  File "test.py", line 233, in main
    delete_files()
  File "test.py", line 183, in delete_files
    shutil.rmtree('ppdata')
  File "/Users/hansen/anaconda/lib/python3.6/shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Users/hansen/anaconda/lib/python3.6/shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "/Users/hansen/anaconda/lib/python3.6/shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [Errno 66] Directory not empty: 'ppdata'
```
which seems not to come as a surprise when looking at the code. It seems like we would want to surround some or all of these tests with
```python
with toolsdivers.Infolder(findfiles.COCODataArchive().local_data_path):
...
```

**Comment by nikohansen** [comment]
One reason for the error on MacOS, I believe, was the file `.DS_Store` which is added to the folder by the system once in a while.
