### ISSUE TITLE
testing error on "newly generated random search data on `bbob-constrained`"

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1602]
from [circleci...728](https://circleci.com/gh/numbbo/coco/728)
```
ALL done (Sat Sep 30 18:36:21 2017).
/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/rungeneric.py:281: UserWarning: "/root/coco/code-experiments/build/python/exdata/RS-co" seems not to be an existing file or match any archived data
  warnings.warn('"%s" seems not to be an existing file or match any archived data' % name)
Post-processing (1)
  Using:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/rungeneric.py", line 329, in main
    ppfigs.get_ecdfs_single_functions_single_dim_caption(), '}']
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/compall/ppfigs.py", line 223, in get_ecdfs_single_functions_single_dim_caption
    return captions.replace(s)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/captions.py", line 36, in replace
    text = text.replace(key, replace_dict[key]())
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.681-py2.7.egg/cocopp/captions.py", line 153, in <lambda>
    '!!TARGET-RANGES-IN-ECDF!!': lambda: str(testbedsettings.current_testbed.pprldmany_target_range_latex),
AttributeError: 'NoneType' object has no attribute 'pprldmany_target_range_latex'
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  93.5456228256  seconds
python -m  cocopp --no-svg --settings=grayscale RS-4.tgz
**  subtest 2 finished in  278.761741161  seconds
Sat Sep 30 18:00:59 2017
**  subtest 3 finished in  201.418315887  seconds
**  subtest 4 finished in  280.525638819  seconds
**  subtest 5 finished in  328.961081982  seconds
**  subtest 6 finished in  82.2773649693  seconds
**  subtest 7 finished in  379.886108875  seconds
**  subtest 8 finished in  308.587293148  seconds
**  subtest 9 finished in  291.408396006  seconds
**  subtest 10 finished in  70.7618730068  seconds
**  subtest 11 finished in  169.116368055  seconds
**  subtest 12 finished in  0.428153991699  seconds
Traceback (most recent call last):
  File "test.py", line 389, in <module>
    main(sys.argv[1:])
  File "test.py", line 330, in main
    assert result == 0, 'Test failed: rungeneric on newly generated random search data on `bbob-constrained`.'
AssertionError: Test failed: rungeneric on newly generated random search data on `bbob-constrained`.

Exited with code 255
```
Maybe someone understands why we see this here? Is it maybe just because `bbob-constrained` is not defined as known suite?

**Comment by nikohansen** [comment]
> Is it maybe just because `bbob-constrained` is not defined as known suite?

That was it.
