### ISSUE TITLE
CI error exdata/RS-co seems not to be an existing file

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1603]
(same as #1602) [from circleci](https://circleci.com/gh/numbbo/coco/746):
```
ALL done (Sun Oct  1 17:45:15 2017).
/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/rungeneric.py:281: UserWarning: "/root/coco/code-experiments/build/python/exdata/RS-co" seems not to be an existing file or match any archived data
  warnings.warn('"%s" seems not to be an existing file or match any archived data' % name)
Post-processing (1)
  Using:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/rungeneric.py", line 329, in main
    ppfigs.get_ecdfs_single_functions_single_dim_caption(), '}']
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/compall/ppfigs.py", line 223, in get_ecdfs_single_functions_single_dim_caption
    return captions.replace(s)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/captions.py", line 36, in replace
    text = text.replace(key, replace_dict[key]())
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.0.686-py2.7.egg/cocopp/captions.py", line 153, in <lambda>
    '!!TARGET-RANGES-IN-ECDF!!': lambda: str(testbedsettings.current_testbed.pprldmany_target_range_latex),
AttributeError: 'NoneType' object has no attribute 'pprldmany_target_range_latex'
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  244.614644051  seconds
python -m  cocopp --no-svg --settings=grayscale RS-4.tgz
**  subtest 2 finished in  198.324934959  seconds
Sun Oct  1 17:12:09 2017
**  subtest 3 finished in  178.63695097  seconds
**  subtest 4 finished in  191.590032816  seconds
**  subtest 5 finished in  343.062988043  seconds
**  subtest 6 finished in  76.6098899841  seconds
**  subtest 7 finished in  378.161370993  seconds
**  subtest 8 finished in  402.917103052  seconds
**  subtest 9 finished in  191.591731071  seconds
**  subtest 10 finished in  64.3390820026  seconds
**  subtest 11 finished in  150.467700005  seconds
**  subtest 12 finished in  0.377846956253  seconds
Traceback (most recent call last):
  File "test.py", line 389, in <module>
    main(sys.argv[1:])
  File "test.py", line 330, in main
    assert result == 0, 'Test failed: rungeneric on newly generated random search data on `bbob-constrained`.'
AssertionError: Test failed: rungeneric on newly generated random search data on `bbob-constrained`.

Exited with code 255
```

**Comment by nikohansen** [comment]
The reason is apparently an outdated `interface.c` file. The strategy to not commit the automatically generated `interface.c` file seems not to be the best of all ideas.
