### ISSUE TITLE
 negative dimensions are not allowed when using  python -m cocopp

### ISSUE THREAD

**Issue by 7belrhalmia** [numbbo/coco#1636]
Hello when I am using this command: python -m cocopp   /home/belr/Desktop/exdata/     

 I got this error : 

Post-processing (1): will generate output data in folder ppdata/exdata
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Scaling figures...
Loading best algorithm data from refalgs/best2016-bbob-biobj.tar.gz ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: /home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/refalgs/best2016-bbob-biobj.tar.gz
  done (Sat Oct 21 13:17:39 2017).
  done (Sat Oct 21 13:19:33 2017).
Generating LaTeX tables...
  done (Sat Oct 21 13:19:34 2017).
ECDF graphs...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/__main__.py", line 373, in <module>
    rungeneric.main(args)
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/rungeneric.py", line 272, in main
    + ["-o", outputdir, alg])
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/rungeneric1.py", line 409, in main
    pprldistr.main(sliceNoise, True, algoutputdir, '%s' % noise)
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/pprldistr.py", line 823, in main
    ** rldStyles[j % len(rldStyles)])
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/pprldistr.py", line 485, in plotRLDistr
    res = plotECDF(x, nn, **kwargs)
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/pprldistr.py", line 368, in plotECDF
    drawstyle='steps', **plotArgs)
  File "/home/belr/.local/lib/python2.7/site-packages/cocopp-2.1-py2.7.egg/cocopp/ppfig.py", line 534, in plotUnifLogXMarkers
    res3 = plt.plot([], [], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 3241, in plot
    ret = ax.plot(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1715, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/axes/_axes.py", line 1436, in plot
    self.add_line(line)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 1759, in add_line
    self._update_line_limits(line)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 1781, in _update_line_limits
    path = line.get_path()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/lines.py", line 951, in get_path
    self.recache()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/lines.py", line 684, in recache
    xy = STEP_LOOKUP_MAP[self._drawstyle](*self._xy.T)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-0_unknown-py2.7-linux-x86_64.egg/matplotlib/cbook/__init__.py", line 2185, in pts_to_prestep
    steps = np.zeros((1 + len(args), 2 * len(x) - 1))
ValueError: negative dimensions are not allowed

I can't show my graphs what is the solution please

**Comment by nikohansen** [comment]
Thanks for the report. I believe this is a bug we have already observed in issue 1481 [here](https://github.com/numbbo/coco/issues/1481#issuecomment-336145194). Due to changes in `matplotlib`, the call `plt.plot([], [], **kwargs)` which worked with older versions (<2.0.2) now fails in version 2.1.

This may be solved with the latest push to the `development` branch. That is

* pull the latest development branch (`git pull`)
* uninstall `cocopp` (`pip uninstall --yes cocopp`)
* install the pulled version with `python do.py install-postprocessing`

Please report back, as I have currently no idea whether the problem is actually solved.
