### ISSUE TITLE
Nightly builds fail after the CloudStack upgrade

### ISSUE THREAD

**Issue by dtusar** [numbbo/coco#1664]
I noticed that the nightly builds fail after the upgrade of CloudStack to version 4.9.3 which was done during the day on the 9th November (I received an email about the upgrade that day). The problem occurs when sending the build status to GitHub:

```
E:\builds\workspace\Coco-dev-nightly-win\dotype\test-preprocessing\label\numbbo-win>exit 0 
Sending e-mails to: dimo.brockhoff@inria.fr dejan.tusar@inria.fr
Setting commit status on GitHub for https://github.com/numbbo/coco/commit/afca518ac73e533af1c398eaec5e10def48534d1
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/numbbo/coco/statuses/afca518ac73e533af1c398eaec5e10def48534d1","id":4313728155,"state":"success","description":"Build #665 succeeded in 47 min","target_url":"https://ci.inria.fr/numbbo/job/Coco-dev-nightly-win/dotype=test-preprocessing,label=numbbo-win/665/","context":"Coco-dev-nightly-win/dotype=test-preprocessing,label=numbbo-win","created_at":"2017-11-14T04:26:55Z","updated_at":"2017-11-14T04:26:55Z","creator":{"login":"dtusar","id":13744819,"avatar_url":"https://avatars2.githubusercontent.com/u/13744819?v=4","gravatar_id":"","url":"https://api.github.com/users/dtusar","html_url":"https://github.com/dtusar","followers_url":"https://api.github.com/users/dtusar/followers","following_url":"https://api.github.com/users/dtusar/following{/other_user}","gists_url":"https://api.github.com/users/dtusar/gists{/gist_id}","starred_url":"https://api.github.com/users/dtusar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dtusar/subscriptions","organizations_url":"https://api.github.com/users/dtusar/orgs","repos_url":"https://api.github.com/users/dtusar/repos","events_url":"https://api.github.com/users/dtusar/events{/privacy}","received_events_url":"https://api.github.com/users/dtusar/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:464)
	at org.kohsuke.github.Requester._to(Requester.java:227)
	at org.kohsuke.github.Requester.to(Requester.java:194)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:829)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:138)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:90)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4313728155) out of range of int
 at [Source: java.io.StringReader@1b46c36c; line: 1, column: 116] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at org.kohsuke.github.Requester.parse(Requester.java:462)
	... 14 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4313728155) out of range of int
 at [Source: java.io.StringReader@1b46c36c; line: 1, column: 116]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 18 more
Finished: FAILURE
```

According to this: https://github.com/jenkinsci/ghprb-plugin/issues/579 the problem should be fixed by upgrading the "GitHub API Plugin" on Jenkins to the latest version. But because the Jenkins version that we use is quite old are there some warnings (check GitHub API Plugin here: https://ci.inria.fr/numbbo/pluginManager/) that discourage me from updating the plugin.

**Comment by brockho** [comment]
I only received "Jenkins build is back to normal" emails in the last days, but you are right: on Jenkins itself, the nightly build is red.

Do you know why your name is appearing in the output such as in:
```
Setting commit status on GitHub for https://github.com/numbbo/coco/commit/afca518ac73e533af1c398eaec5e10def48534d1
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/numbbo/coco/statuses/afca518ac73e533af1c398eaec5e10def48534d1","id":4313744822,"state":"success","description":"Build #655 succeeded in 1 hr 5 min","target_url":"https://ci.inria.fr/numbbo/job/Coco-dev-nightly/dotype=test-postprocessing-all,label=numbbo-osx10p12/655/","context":"Coco-dev-nightly/dotype=test-postprocessing-all,label=numbbo-osx10p12","created_at":"2017-11-14T04:42:45Z","updated_at":"2017-11-14T04:42:45Z","creator":{"login":"dtusar","id":13744819,"avatar_url":"https://avatars2.githubusercontent.com/u/13744819?v=4","gravatar_id":"","url":"https://api.github.com/users/dtusar","html_url":"https://github.com/dtusar","followers_url":"https://api.github.com/users/dtusar/followers","following_url":"https://api.github.com/users/dtusar/following{/other_user}","gists_url":"https://api.github.com/users/dtusar/gists{/gist_id}","starred_url":"https://api.github.com/users/dtusar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dtusar/subscriptions","organizations_url":"https://api.github.com/users/dtusar/orgs","repos_url":"https://api.github.com/users/dtusar/repos","events_url":"https://api.github.com/users/dtusar/events{/privacy}","received_events_url":"https://api.github.com/users/dtusar/received_events","type":"User","site_admin":false}}
```
The credentials are still set to "NumbboCI" in Jenkins.

**Comment by dtusar** [comment]
Not sure but the problem is explained in this line:
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4313728155) out of range of int
 at [Source: java.io.StringReader@1b46c36c; line: 1, column: 116]
```
and it's not related to the credentials.

**Comment by brockho** [comment]
This issue is solved, I would guess, thanks to @dtusar "wrestling" well with Jenkins last week :-)
