### ISSUE TITLE
Post-processing issue - wrong results

### ISSUE THREAD

**Issue by pmarchne** [numbbo/coco#1700]
Hello, I am simply trying to post-process the 'example_experiment.py' but I can't fix the following error:

<pre><code> $ python -m cocopp exdata/

Post-processing (1): will generate output data in folder ppdata/exdata
  this might take several minutes.
/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/pproc.py:1085: UserWarning:   instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016
  warnings.warn('  instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016')
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder /home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/refalgs/_extracted_best2009-bbob ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: /home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/refalgs/best2009-bbob.tar.gz
  done (Sun Jan 14 19:36:45 2018).
  done (Sun Jan 14 19:37:01 2018).
Generating LaTeX tables...
  done (Sun Jan 14 19:37:01 2018).
ECDF graphs...
  done (Sun Jan 14 19:37:13 2018).
ECDF graphs per function...
/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/compall/pprldmany.py:321: RuntimeWarning: invalid value encountered in less_equal
  tmp = (x2 <= maxval)
/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/compall/pprldmany.py:323: RuntimeWarning: invalid value encountered in less
  x2bis = x2[y2 < y2[tmp][-1]][-1]
Traceback (most recent call last):
  File "/home/philippe/anaconda3/envs/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/philippe/anaconda3/envs/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/__main__.py", line 373, in <module>
    rungeneric.main(args)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/rungeneric.py", line 272, in main
    + ["-o", outputdir, alg])
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/rungeneric1.py", line 429, in main
    settings=inset)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/compall/pprldmany.py", line 468, in all_single_functions
    settings=settings)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/compall/pprldmany.py", line 837, in main
    ppfig.save_figure(figureName, dictAlg[algorithms_with_data[0]][0].algId)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-0.0.0-py2.7.egg/cocopp/ppfig.py", line 68, in save_figure
    bbox_inches=bbox_inches_choices.get(format, None)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1193, in print_svg
    return self._print_svg(filename, svgwriter, **kwargs)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1238, in _print_svg
    self.figure.set_dpi(72.0)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 811, in set_dpi
    self.dpi = val
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 436, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "/home/philippe/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 733, in set_size_inches
    '({}, {})'.format(w, h))
ValueError: figure size must be finite not (nan, nan)
(python2) </code></pre>

I'm using:
- Xubuntu 16.04
- Python 2.7.14 :: Anaconda, Inc.
- numpy 1.14.0
- matplotlib 2.1.1

I had not problem while running '$ python example_experiment.py bbob'

I would be grateful for any help !

**Comment by pmarchne** [comment]
Dear Dimo, thanks for your response.

I reinstalled cocopp (I both used pip and removed all the files with cocopp*.egg), but I got the same error message.
<pre><code>
$ python -m cocopp -o ppdata exdata/random_search_on_bbob_budget0002xD/

Post-processing (1): will generate output data in folder ppdata/random_search_on_bbob_budget0002xD
  this might take several minutes.
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/pproc.py:1085: UserWarning:   instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016
  warnings.warn('  instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016')
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: /home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/refalgs/best2009-bbob.tar.gz
  done (Tue Jan 16 14:24:22 2018).
  done (Tue Jan 16 14:24:39 2018).
Generating LaTeX tables...
  done (Tue Jan 16 14:24:39 2018).
ECDF graphs...
  done (Tue Jan 16 14:24:50 2018).
ECDF graphs per function...
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py:321: RuntimeWarning: invalid value encountered in less_equal
  tmp = (x2 <= maxval)
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py:323: RuntimeWarning: invalid value encountered in less
  x2bis = x2[y2 < y2[tmp][-1]][-1]
Traceback (most recent call last):
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/__main__.py", line 373, in <module>
    rungeneric.main(args)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/rungeneric.py", line 272, in main
    + ["-o", outputdir, alg])
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/rungeneric1.py", line 429, in main
    settings=inset)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py", line 468, in all_single_functions
    settings=settings)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py", line 837, in main
    ppfig.save_figure(figureName, dictAlg[algorithms_with_data[0]][0].algId)
  File "/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/ppfig.py", line 68, in save_figure
    bbox_inches=bbox_inches_choices.get(format, None)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1193, in print_svg
    return self._print_svg(filename, svgwriter, **kwargs)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1238, in _print_svg
    self.figure.set_dpi(72.0)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/figure.py", line 811, in set_dpi
    self.dpi = val
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/figure.py", line 436, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "/home/philippe/anaconda3/envs/python27/lib/python2.7/site-packages/matplotlib/figure.py", line 733, in set_size_inches
    '({}, {})'.format(w, h))
ValueError: figure size must be finite not (nan, nan)
(python27)
</code></pre>
I tried to downgrade my matplotlib to 2.0.2, and I got a slightly different message:
<pre><code>
$ python -m cocopp -o ppdata exdata/random_search_on_bbob_budget0002xD/

Post-processing (1): will generate output data in folder ppdata/random_search_on_bbob_budget0002xD
  this might take several minutes.
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/pproc.py:1085: UserWarning:   instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016
  warnings.warn('  instance numbers not among the ones specified in 2009, 2010, 2012, 2013, 2015 or 2016')
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder /home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/refalgs/_extracted_best2009-bbob ...
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: /home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/refalgs/best2009-bbob.tar.gz
  done (Tue Jan 16 14:21:51 2018).
  done (Tue Jan 16 14:22:07 2018).
Generating LaTeX tables...
  done (Tue Jan 16 14:22:07 2018).
ECDF graphs...
  done (Tue Jan 16 14:22:23 2018).
ECDF graphs per function...
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py:321: RuntimeWarning: invalid value encountered in less_equal
  tmp = (x2 <= maxval)
/home/philippe/.local/lib/python2.7/site-packages/cocopp-2.1.1-py2.7.egg/cocopp/compall/pprldmany.py:323: RuntimeWarning: invalid value encountered in less
  x2bis = x2[y2 < y2[tmp][-1]][-1]
  done (Tue Jan 16 14:22:51 2018).
aRT loss ratio figures and tables...
  done (Tue Jan 16 14:22:57 2018).
Output data written to folder ppdata
  done (Tue Jan 16 14:22:57 2018).
(python27)
</code></pre>
This seems better but the resulting figures are still not as expected.
I tried different versions of setuptools and numpy, but I did not notice any change.

**Comment by pmarchne** [comment]
Here is a screenshot of what I obtain for <code>ppfigdim.html</code> with matplotlib 2.0.2 after the post-processing. I might be wrong, but I don't think these plots are correct, or are they ?

![example_experiment_ppfigdim](https://user-images.githubusercontent.com/32577622/35013015-247f918e-fb0c-11e7-8979-9eae21346689.png)
 I used <code>$ python example_experiment.py bbob</code> for the calculation.

**Comment by brockho** [comment]
I don't see anything wrong in the plots. When I run the example experiment myself with RANDOMSEARCH as algorithm and postprocess the result, it looks very similar to your plots. If you can point us directly to what you think is not correct, we might also see it :-)
I agree that a label "nothing to plot" in the plots without markers will be more desirable, but again I do not see anything wrong with the plots per se. Run the experiment longer and you should start seeing labels also for more and more functions,

**Comment by pmarchne** [comment]
I'm sorry I was confused because I could not see any curves in some plots. I tried with other data/algorithms and it works well.

Thanks a lot for your help !

**Comment by nikohansen** [comment]
This is probably a bug in the `master` branch which was already fixed in the `development` branch. If it's still a problem in the `development` branch, please let us know.

**Comment by nikohansen** [comment]
A quick search revealed several usages of `plt.plot([], [],...` in the code.
