### ISSUE TITLE
When no archive algorithm matches the user's choice

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1812]
Trying to choose a non-existing algorithm in our data archive results in a cryptic message:
```
C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python -m cocopp -o ppdataOLD20 ALPS! BAYE! BFGS! 2017/BF!
Post-processing (2+)
  Using:
    C:\Users\dimo\.cocopp\data-archive\bbob\2009\ALPS_hornby_noiseless.tgz
    C:\Users\dimo\.cocopp\data-archive\bbob\2009\BAYEDA_gallagher_noiseless.tgz
    C:\Users\dimo\.cocopp\data-archive\bbob\2009\BFGS_ros_noiseless.tgz
    None
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.2.1.221-py2.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.2.1.221-py2.7.egg\cocopp\rungeneric.py", line 308, in main
    if data_archive.contains(path):  # this is the archive of *all* testbeds
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.2.1.221-py2.7.egg\cocopp\archiving.py", line 872, in contains
    return self._name(name) in self
  File "C:\Users\dimo\Anaconda2\lib\site-packages\cocopp-2.2.1.221-py2.7.egg\cocopp\archiving.py", line 864, in _name
    if full_path.startswith(self.local_data_path):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Nicer would be if the user gets a bit more assistance than just seeing the "None". In the case of non-uniqueness of the user's choice, the data archive also gives more information about the error itself.

**Comment by nikohansen** [comment]
Fixed with commit d590d06a1
