### ISSUE TITLE
Unclosed file error

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#1879]
I'm trying to launch batches job of Matlab COCO experiments in the same way [as done with Python experiments](https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example_experiment2.py).

To check if everything went well I downloaded data from a remote machine while some batch processes were still running, and wanted to post process this data on my machine

Apart from issues I have with my own code, this warning is thrown and may be handled on  the cocopp side.

```
pol@debian:~/workspace/1+1_mo_cma_es/exdata_test_batch$ python -m cocopp .
Post-processing (1)
  Using:
    ./.

Post-processing (1)
Traceback (most recent call last):
  File "/home/pol/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pol/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/rungeneric.py", line 311, in main
    dsld = rungeneric1.main(genopts + ["-o", outputdir, alg])
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/rungeneric1.py", line 274, in main
    dsList = DataSetList(filelist)
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/pproc.py", line 1712, in __init__
    self.processIndexFile(name)
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/pproc.py", line 1783, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)                    
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/pproc.py", line 915, in __init__
    align_data, data, self)
  File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/dataformatsettings.py", line 37, in align_data_into_evals
    assert all(dataset.evals[0][1:] == 1)
AssertionError
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='././test_batch/MOCMAES_on_bbob-biobj_batch2/1-separable_2-moderate_hyp.info' mode='r' encoding='UTF-8'>
```

**Comment by nikohansen** [comment]
The culprit seems to be that the assert
```
File "/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/cocopp-2.2.1.10-py3.6.egg/cocopp/dataformatsettings.py", line 37, in align_data_into_evals
    assert all(dataset.evals[0][1:] == 1)
AssertionError
```
fails, which probably means there is an instance with not even a single evaluation. As it is based on user data, it should not throw an assert error, but a value error. More importantly, this should however (preferably) not lead to a bail out at all.

**Comment by brockho** [comment]
It seems to be unlikely enough that the above error occurs that we decided together with @ttusar and @nikohansen to close the issue.
