### ISSUE TITLE
Nightly test failure

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1893]
Fails with the message that `testbedsettings.current_testbed.pprldmany_target_range_latex` is missing for the large-scale testbed?

```
File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.25-py2.7.egg\cocopp\captions.py", line 162, in <lambda>
    '!!TARGET-RANGES-IN-ECDF!!': lambda: str(testbedsettings.current_testbed.pprldmany_target_range_latex),
AttributeError: 'NoneType' object has no attribute 'pprldmany_target_range_latex'
*** testing module cocopp ***

. 
. 
. 

**  subtest 14 finished in  0.858999967575  seconds
Traceback (most recent call last):
  File "test.py", line 451, in <module>
  File "test.py", line 386, in main
AssertionError: Test failed: rungeneric on newly generated random search data on `bbob-largescale`.
```

**Comment by nikohansen** [comment]
Similar or same problem again, testing `bbob-largescale` fails, I guess because some parts of the code do not (yet) know about this testbed?

```
[...]
Post-processing (1)
  Using:
    C:\Users\ci\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\test\RS-4.zip

Post-processing (1)
  Data consistent according to consistency_check() in pproc.DataSet
  Will generate output data in folder ppdata\RS-4.zi
    this might take several minutes.
Scaling figures...
Loading best algorithm data from refalgs/best2016-bbob-biobj.tar.gz ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: c:\programdata\anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\refalgs/best2016-bbob-biobj.tar.gz
  done (Sun May 26 05:28:53 2019).
{message : RuntimeWarning('invalid value encountered in absolute',), category : 'RuntimeWarning', filename : 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\matplotlib\\transforms.py', lineno : 661, line : None}
while saving figure in "ppdata\RS-4.zi\ppfigdim_f001" (in ppfigdim.py:551)
  done (Sun May 26 05:29:28 2019).
Generating LaTeX tables...
  done (Sun May 26 05:29:28 2019).
ECDF graphs...
  done (Sun May 26 05:30:01 2019).
ECDF graphs per function...
  done (Sun May 26 05:31:21 2019).
aRT loss ratio figures and tables...
  done (Sun May 26 05:31:41 2019).
Output data written to folder c:\users\ci\appdata\local\temp\_lgkjn3\ppdata\RS-4.zi
Setting changes in `cocopp.genericsettings` compared to default:
    interactive_mode: from True to False
    foreground_algorithm_list: from [] to [u'C:\\Users\\ci\\.coc...
    inputsettings: from "color" to "grayscale"
ALL done (Sun May 26 05:31:41 2019).
C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\rungeneric1.py:234: UserWarning: grayscalesettings disregarded
  warnings.warn("grayscalesettings disregarded")
C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\readalign.py:269: RuntimeWarning: divide by zero encountered in log10
  numpy.ceil(numpy.log10(max(fvalues) - 1e-12) * self.nbPtsF))
C:\ProgramData\Anaconda2\lib\site-packages\matplotlib\axes\_base.py:2917: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=100000.0, right=100000.0
  'left=%s, right=%s') % (left, right))
Post-processing (1)
C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\archiving.py:729: UserWarning: "E:\builds\workspace\Coco-dev-nightly-win\dotype\test-postprocessing-all\label\numbbo-win\code-experiments\build\python\exdata\RS-la" seems not to be an existing file or match any archived data
  'match any archived data' % name)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\rungeneric.py", line 293, in main
    args = data_archive.get_extended(args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.28-py2.7.egg\cocopp\archiving.py", line 731, in get_extended
    'match any archived data' % name)
ValueError: "E:\builds\workspace\Coco-dev-nightly-win\dotype\test-postprocessing-all\label\numbbo-win\code-experiments\build\python\exdata\RS-la" seems not to be an existing file or match any archived data
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
[...]
```

**Comment by nikohansen** [comment]
We found a possible explanation: the download path for the test data changed at some point from a shorter path to `~.cocopp/data-archives/coco.gforge.inria.fr/data-archive/`.

**Comment by nikohansen** [comment]
We still have the same error.
```
ALL done (Fri May 31 05:29:53 2019).
C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.30-py2.7.egg\cocopp\rungeneric1.py:234: UserWarning: grayscalesettings disregarded
  warnings.warn("grayscalesettings disregarded")
C:\ProgramData\Anaconda2\lib\site-packages\matplotlib\axes\_base.py:2917: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=100000.0, right=100000.0
  'left=%s, right=%s') % (left, right))
Post-processing (1)
C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.30-py2.7.egg\cocopp\archiving.py:729: UserWarning: "E:\builds\workspace\Coco-dev-nightly-win\dotype\test-postprocessing-all\label\numbbo-win\code-experiments\build\python\exdata\RS-la" seems not to be an existing file or match any archived data
  'match any archived data' % name)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.30-py2.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.30-py2.7.egg\cocopp\rungeneric.py", line 293, in main
    args = data_archive.get_extended(args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cocopp-2.3.1.30-py2.7.egg\cocopp\archiving.py", line 731, in get_extended
    'match any archived data' % name)
ValueError: "E:\builds\workspace\Coco-dev-nightly-win\dotype\test-postprocessing-all\label\numbbo-win\code-experiments\build\python\exdata\RS-la" seems not to be an existing file or match any archived data
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  91.8320000172  seconds
python -m  cocopp --no-svg --settings=grayscale RANDOMSEARCH-4_Auger_bbob-biobj.tgz
**  subtest 2 finished in  178.051000118  seconds
Fri May 31 04:56:09 2019
**  subtest 3 finished in  180.075999975  seconds
**  subtest 4 finished in  202.404000044  seconds
**  subtest 5 finished in  322.447999954  seconds
**  subtest 6 finished in  84.3599998951  seconds
**  subtest 7 finished in  341.455000162  seconds
**  subtest 8 finished in  292.398000002  seconds
**  subtest 9 finished in  185.309000015  seconds
**  subtest 10 finished in  70.4790000916  seconds
**  subtest 11 finished in  159.882999897  seconds
**  subtest 13 finished in  183.953999996  seconds
**  subtest 14 finished in  0.853000164032  seconds
Traceback (most recent call last):
  File "test.py", line 451, in <module>
  File "test.py", line 386, in main
AssertionError: Test failed: rungeneric on newly generated random search data on `bbob-largescale`.
```
