### ISSUE TITLE
"The path is too long" error with data archive

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1901]
I updated the archive definition file with the newest BBOB-2019 results. Unfortunately, the new data archiving strategy to use the full path when downloading creates a "too long path" error on my Windows machine:

```
C:\Users\dimo\Desktop\dataBBOB2019-Cheikh>python -m cocopp UP- COMO-10_ GDE3
Post-processing (2+)
  Using:
    C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2016\UP-MO-CMA-ES_Krause_bbob-biobj.tgz
    C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2019\como-10_biobj_dufosse_toure.tgz
    C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2019\GDE3-platypus_biobj_Brockhoff_Tusar.tgz

Post-processing (2+)
  loading data...
    archive extracted to folder C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2016\.extracted_UP-MO-CMA-ES_Krause_bbob-biobj ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2016\UP-MO-CMA-ES_Krause_bbob-biobj.tgz
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\dimo\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\rungeneric.py", line 332, in main
    dsld = rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\rungenericmany.py", line 290, in main
    dsList, sortedAlgs, dictAlg = processInputArgs(args, True)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\pproc.py", line 2725, in processInputArgs
    process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\pproc.py", line 2743, in process_arguments
    filelist = findfiles.main(i)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\findfiles.py", line 52, in main
    directory = get_directory(directory, True)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.31-py3.7.egg\cocopp\findfiles.py", line 110, in get_directory
    'from "%s". The path is too long.' % directory)
FileNotFoundError: [Errno 2] Some of the files cannot be extracted from "C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\bbob-biobj\2019\como-10_biobj_dufosse_toure.tgz". The path is too long.
```

Do we really need the two `data-archives`/`data-archive` in the path? Otherwise, we might have to go back to removing the author names (I am definitely not in favor of the latter). The other option is to reorganize the data within the `.tgz` to have shorter (sub-)folders.

**Comment by brockho** [comment]
I reduced the lengths of the path names within the `como` data sets by about 30 characters and it works now for me.
