### ISSUE TITLE
Can we postprocess joint bbob and bbob-largescale data?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1960]
We have implemented the filtering to compare `bbob` with `bbob-largescale` data sets, but we should also make sure that a single folder with data in dimensions in 2-640 can be postprocessed correctly (and identified as `BBOBLargeScaleJOINEDTestbed`). Maybe this already works out of the box (to be tested).

**Comment by brockho** [comment]
It turns out that a single data set, comprised of both `bbob` and `bbob-largescale` data for the same algorithm cannot be postprocessed right now:
```
C:\Users\dimo\Desktop\coco\code-experiments\build\python\exdata>python -m cocopp slsqp-joint
C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\archiving.py:200: UserWarning: could not move the official archive location
C:\Users\dimo\.cocopp\data-archive
 because
C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr
 already exists.
To prevent this message in future, remove either one or the other folder (preferably the smaller one)
  " the other folder (preferably the smaller one)" % (src, dest))
Post-processing (1)
  Using:
    slsqp-joint

Post-processing (1)
C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\pproc.py:1094: UserWarning:   double instances in [1, 2, 3, 4, 5, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] (f1, 20D)
  + 'D)')
  Will generate output data in folder ppdata\slsqp-joint
    this might take several minutes.
Scaling figures...
Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: c:\users\dimo\anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\refalgs/best2009-bbob.tar.gz
  done (Wed May  6 09:29:48 2020).
  done (Wed May  6 09:30:12 2020).
Generating LaTeX tables...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\dimo\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\rungeneric.py", line 395, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\rungeneric1.py", line 176, in main
    pptable.main(sliceNoise, dims, algoutputdir, latex_commands_file)
  File "C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.3.34-py3.7.egg\cocopp\pptable.py", line 174, in main
    refalgentry = refalgentries[(d, f)]
KeyError: (80, 1)
```
Together with another purely `bbob-largescale` data set, things work well because the postprocessing detects both `bbob` (for the joint data set) and `bbob-largescale` data sets and thus uses the `BBOBLargeScaleJOINEDTestbed` test bed class correctly.

**Comment by brockho** [comment]
Solved now in `development` branch.
