### ISSUE TITLE
Error when post-processing experiment in batches

### ISSUE THREAD

**Issue by rickboks** [numbbo/coco#2014]
**Describe the bug**
I ran an experiment on BBOB in 32 batches, and moved all 'batch' folders into one root folder. So, the directory structure of the produced data looks like this: 

|- AlgId
|--- AlgId_batch001of32
|...
|--- AlgId_batch032of32

Running the post-processing on this **one** folder like this works fine: 
```
python -m cocopp AlgId
```
But when comparing multiple algorithms, the post-processing throws an error: 
```
could not convert string to float: '8.7e-09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 [...etc]
```
This happens both when:
- comparing the 'batched' experiment with an experiment that was run in a single batch; and when
- comparing the 'batched' experiment with an experiment that was run in the same number of batches.

It works fine when comparing multiple algorithms that were run in a single batch. 
Thanks for the great tool!

**Your System (please complete the following information when it seems relevant):**
 - Operating system: Arch Linux 5.11.16
 - COCO version: 2.4

**Comment by rickboks** [comment]
Full error message: 

```
/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py:989: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
Traceback (most recent call last):
  File "/home/rick/anaconda3/envs/bbob/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rick/anaconda3/envs/bbob/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/rungeneric.py", line 404, in main
    dsld = rungenericmany.main(args, outputdir)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/rungenericmany.py", line 112, in main
    dsList, sortedAlgs, dictAlg = processInputArgs(args, True)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py", line 2760, in processInputArgs
    process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py", line 2784, in process_arguments
    tmpDsList = DataSetList(alg)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py", line 1789, in __init__
    self.processIndexFile(name, alg_name)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py", line 1878, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)
  File "/home/rick/.local/lib/python3.6/site-packages/cocopp/pproc.py", line 895, in __init__
    self.readfinalFminusFtarget.append(float(readfinalf))
ValueError: could not convert string to float: '8.7e-09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by rickboks** [comment]
The error was caused by my own fault, resulting in invalid data files ... closing issue.
