### ISSUE TITLE
[Bug report] UnicodeDecodeError when installing Python version

### ISSUE THREAD

**Issue by MrDomani** [numbbo/coco#2025]
When installing the Python version of coco by step 3 (running python do.py run-python in console) the cmd brings following output:

AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testcases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install in code-experiments\build\python
Traceback (most recent call last):
  File "do.py", line 1032, in <module>
    main(sys.argv[1:])
  File "do.py", line 1001, in main
    elif cmd == 'build-python': build_python(package_install_option = package_install_option)
  File "do.py", line 326, in build_python
    python(join('code-experiments', 'build', 'python'), ['setup.py', 'install']
  File "D:\Programy\coco\code-experiments\tools\cocoutils.py", line 144, in python
    output = check_output_with_print(verbose, full_command, stderr=STDOUT, env=os.environ,
  File "D:\Programy\coco\code-experiments\tools\cocoutils.py", line 43, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "E:\anaconda\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\anaconda\lib\subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "E:\anaconda\lib\subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
  File "E:\anaconda\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 2099: character maps to <undefined>

Tried reinstalling anaconda, deinstalling anaconda and running with pure python, executing from system cmd, Powershell and their Anaconda counterparts. Also changed system language to English (normally is in Polish). The same bug appears everytime.

System:
 - Operating system: Windows 10
 - COCO version: newest, downloaded with git clone as in step 2
 - Cygwin installed
 - Tried Python 3.10 and Anaconda with Python 3.8
 - Polish locale

**Comment by nikohansen** [comment]
This suggests, to try `'1250'` or (equivalently) `locale.getlocale()[1]` as encoding in line 145 of `coco\code-experiments\tools\cocoutils.py`, or possibly use `locale.setlocal` to change localization.

**Comment by MrDomani** [comment]
Right now they're both on the same partition of the same disk. Thanks for the idea though

**Comment by nikohansen** [comment]
Cool, to make this work for everybody we probably want to get rid of the `universal_newlines` then, and this should not have other adverse effects?
