### ISSUE TITLE
[Bug report] postprocessing fails tests

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2066]
**Describe the bug**
The latest commit to development fails the postprocessing test which seems to come directly on import of `cocopp`. I ran for example on the ubuntu Jenkins machine in a python shell:

```
>>> import cocopp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.4.117-py2.7.egg/cocopp/__init__.py", line 102, in <module>
    from .cococommands import *  # outdated
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.4.117-py2.7.egg/cocopp/cococommands.py", line 63, in <module>
    from .pproc import DataSetList as _DataSetList
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.4.117-py2.7.egg/cocopp/pproc.py", line 41, in <module>
    from .ppfig import consecutiveNumbers, Usage
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.4.117-py2.7.egg/cocopp/ppfig.py", line 21, in <module>
    from .captions import get_reference_algorithm_text
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.4.117-py2.7.egg/cocopp/captions.py", line 15, in <module>
    from . import pproc, toolsdivers
ImportError: cannot import name pproc
>>>
```

The corresponding blame of `captions.py` tells me that it was me committing these lines, but also that the change was 5 years ago.

**Your System (please complete the following information when it seems relevant):**
 - Operating system: all current Jenkins machines, on my Windows laptop, the same test runs through
 - COCO version: latest `development` branch, ...]

**Comment by brockho** [comment]
It was actually a circular import that I have introduced myself. The corresponding commit is now reverted in the development branch and which is green again.
