### ISSUE TITLE
[Bug report] cocopp error with bbob-constrained data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2106]
**Describe the bug**
The postprocessing in current `development` branch does not work anymore with data sets from the `bbob-constrained` suite anymore (I used the one from here: #2094):

```python
>> python -m cocopp rs.zip
Post-processing (1)
  Using 1 data set:
    rs.zip

Post-processing (1)
  loading data...
    archive extracted to folder .extracted_rs ...
Traceback (most recent call last):
  File "C:\Users\dimo\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dimo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\rungeneric.py", line 408, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\rungeneric1.py", line 72, in main
    dsList = DataSetList(alg)
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\pproc.py", line 2149, in __init__
    self.processIndexFile(name, alg_name)
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\pproc.py", line 2243, in processIndexFile
    self.append(ds)
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\pproc.py", line 2293, in append
    i.computeERTfromEvals()
  File "C:\Users\dimo\anaconda3\lib\site-packages\cocopp-2.6.1.11-py3.9.egg\cocopp\pproc.py", line 1096, in computeERTfromEvals
    s += sum(self.maxevals[np.logical_not(succ)])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 2
```

@paulduf narrowed the error down to this commit 6294fda2a6 (everything works well before this), so it should be easy to fix?

It suggests that we, as soon as possible, add a test on some `bbob-constrained` data to the nightly build. [I will take care of that]

**Your System (please complete the following information when it seems relevant):**
 - Operating system: both on Windows and Linux
 - COCO version: latest development branch
 - Browser irrelevant

**Comment by nikohansen** [comment]
First hunch: the attribute `_lasttdatfilelines` which is used to compute `maxfgevals` is only set after the above call of `computeERTfromEvals`.

**Comment by nikohansen** [comment]
I hope commit 6288ed3893a14b5c9692c243ccb84fa10cb60ed8 fixes this, you may`git checkout` this commit and test with data from the constrained testbed.

**Comment by brockho** [comment]
Yes, the commit works for me. Thanks!

Given that we now have a corresponding test in the nightly build (within the `development` branch), we should push this/these commit(s) there.
