### ISSUE TITLE
Nightly test failed

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2109]
```
ALL done (Sat Apr 23 12:38:24 2022).
Post-processing (2+)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/rungeneric.py", line 377, in main
    args = data_archive.get_extended(args)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/archiving.py", line 725, in get_extended
    res.append(self.get_first([name[:-1]], remote=remote))
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/archiving.py", line 608, in get_first
    return self.get(self.found[0], remote=remote)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/archiving.py", line 665, in get
    self.check_hash(full_name)
  File "/usr/local/lib/python2.7/dist-packages/cocopp-2.6.1.18-py2.7.egg/cocopp/archiving.py", line 839, in check_hash
    self.full_path(name)))
ValueError: wrong checksum for

   /builds/.cocopp/data-archives/numbbo.github.io/data-archive/data-archive/bbob-biobj/2019/IBEA-platypus_Brockhoff_bbob-biobj.tgz

 in archive

   /builds/.cocopp/data-archives/numbbo.github.io/data-archive/data-archive
   https://numbbo.github.io/data-archive/data-archive

Consider to (re)move file
   /builds/.cocopp/data-archives/numbbo.github.io/data-archive/data-archive/bbob-biobj/2019/IBEA-platypus_Brockhoff_bbob-biobj.tgz
as it may be a partial or unsuccessful download.
A missing file will be downloaded again by `get`.
Alternatively, call `update` to update definitions
and checksums and allow for automatic re-downloads.
If this is not a remote archive consider to re-`create` it.
*** testing module cocopp ***
```
https://ci.inria.fr/numbbo/job/Coco-dev-nightly/dotype=test-postprocessing-all,label=numbbo-ubuntu-12p04-i386/1941/console

**Comment by brockho** [comment]
I removed the `IBEA-platypus` data set locally on the machine and the latest test ran again through.
