### ISSUE TITLE
Issue with cocoex

### ISSUE THREAD

**Issue by ibadis** [numbbo/coco#2136]
Trying to install coco on macOS, having this issue with cocoex.
Installed cocoex and uninstalled still having issues with import Suite from cocoex
```
sudo python3 do.py run-python --user
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
EXPAND	code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY	code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
COPY	code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testcases2.txt
COPY	code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND	code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON	setup.py install --user in code-experiments/build/python
PYTHON	example_experiment.py bbob in code-experiments/build/python
ERROR: return value=1
Traceback (most recent call last):
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 21, in <module>
ImportError: cannot import name '_interface' from 'cocoex' (/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_experiment.py", line 46, in <module>
    import cocoex
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 27, in <module>
ImportError: cannot import name 'Suite' from 'cocoex.interface' (/Users/al-ibadi.s/Library/Caches/Python-Eggs/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg-tmp/cocoex/interface.cpython-38-darwin.so)
```

**Comment by nikohansen** [comment]
Are you sure you need `sudo` to do this installation? This could be a potential problem. Otherwise, I'd also try calling `pip uninstall cocoex` several times until no installation is found and start from there.

Do you get the same problem when executing
```
./do.py build-python --user
python
>>> import cocoex
```

**Comment by ibadis** [comment]
I appreciate the swift reply, thank you very much.
I tried a few things to fix it and the last thing I ran was the `sudo` command, but I tried without as well

Calling `pip3 uninstall cocoex` gives the following output

```
pip3 uninstall cocoex                                                                                                             
Found existing installation: cocoex 2.6.2
Uninstalling cocoex-2.6.2:
  Would remove:
    /Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg
Proceed (Y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/pip/_internal/commands/uninstall.py", line 98, in run
    uninstall_pathset = req.uninstall(
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/pip/_internal/req/req_install.py", line 658, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/pip/_internal/req/req_uninstall.py", line 377, in remove
    pth.remove()
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/pip/_internal/req/req_uninstall.py", line 630, in remove
    with open(self.file, "wb") as fh:
PermissionError: [Errno 13] Permission denied: '/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/easy-install.pth'
```

Until it gave the following output
```
pip3 uninstall cocoex                                                                                                                  
WARNING: Skipping cocoex as it is not installed.
```

Executing `./do.py build-python --user`
```
env: python: No such file or directory
```

Running `python3 do.py build-python --user`
```
python3 do.py build-python --user                                                                                                                       
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testcases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments/build/python

An exception occurred while trying to install packages.

A common reason for this error is insufficient access rights
to the installation directory. The original exception message
is as follows:

/----------------------------< EXCEPTION MESSAGE >----------------------------\
|                                                                             |
| NOTE: Using precompiled C file to build interface.                          |
| running install                                                             |
| running bdist_egg                                                           |
| running egg_info                                                            |
| error: [Errno 13] Permission denied                                         |
\-----------------------------------------------------------------------------/

To fix an access rights issue, you may try the following:

- Run the same command with "install-user" as additional argument.
  To get further help run do.py without a specific command.

- On *nix systems or MacOS, run the same command with a preceded "sudo ".

- Gain write access to the installation directory by changing
  access permissions or gaining administrative access.
```

Then running `sudo python3 do.py run-python --user`
```
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testcases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments/build/python
PYTHON  example_experiment.py bbob in code-experiments/build/python
ERROR: return value=1
Traceback (most recent call last):
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 21, in <module>
ImportError: cannot import name '_interface' from 'cocoex' (/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_experiment.py", line 46, in <module>
    import cocoex
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 27, in <module>
ImportError: cannot import name 'Suite' from 'cocoex.interface' (/Users/al-ibadi.s/Library/Caches/Python-Eggs/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg-tmp/cocoex/interface.cpython-38-darwin.so)
```

Apologies if my comment lacks the information required for you to help me, I am not really into coding/programming, I am setting up coco on behalf of a developer on a new machine.

**Comment by nikohansen** [comment]
I am very much in the dark.
```
PYTHON  setup.py install --user in code-experiments/build/python
```
seems to run through, that is, the `cocoex` module is installed. I'd still want to check whether
```
python3
>>> import cocoex
```
produces the same import error.

It may be a cython problem (is cython installed?) or a problem related to xcode or C-compilation, but I don't have any specific lead. I assume that the C-version runs without problem (which makes an xcode problem unlikely)?

```
python3 do.py run-c
```

**Comment by ibadis** [comment]
Hello, sorry for the late reply!!

So I did the following like you requested and this is the output I got

```
python3                                                                                                                                                             
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cocoex
Traceback (most recent call last):
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 21, in <module>
ImportError: cannot import name '_interface' from 'cocoex' (/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/al-ibadi.s/Library/Python/3.8/lib/python/site-packages/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg/cocoex/__init__.py", line 27, in <module>
ImportError: cannot import name 'Suite' from 'cocoex.interface' (/Users/al-ibadi.s/Library/Caches/Python-Eggs/cocoex-2.6.2-py3.8-macosx-10.14-arm64.egg-tmp/cocoex/interface.cpython-38-darwin.so)
```

And here is the output you requested with running C-version
```
sudo python3 do.py run-c --user                                                                                                                              
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/c/coco.c
EXPAND  code-experiments/build/c/coco.c.in to code-experiments/build/c/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/c/coco.h
COPY    code-experiments/build/c/coco.c -> code-experiments/examples/bbob2009-c-cmaes/coco.c
COPY    code-experiments/build/c/coco.h -> code-experiments/examples/bbob2009-c-cmaes/coco.h
WRITE   code-experiments/build/c/REVISION
WRITE   code-experiments/build/c/VERSION
MAKE    clean in code-experiments/build/c
CHDIR   /Users/al-ibadi.s/Downloads/coco-2.6.2/code-experiments/build/c
COPY    Makefile.in -> Makefile
rm -f coco.o 
rm -f example_experiment.o example_experiment 

MAKE    all in code-experiments/build/c
CHDIR   /Users/al-ibadi.s/Downloads/coco-2.6.2/code-experiments/build/c
COPY    Makefile.in -> Makefile
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment coco.o example_experiment.o -lm  

RUN     ./example_experiment in code-experiments/build/c
```

Is it possible that I have multiple python3s that are conflicting with one another or something along those lines?

**Comment by ibadis** [comment]
Hello, so I think the problem was fixed by running this command. I really don't know what happened but it seems to be working now.

`sudo python3 do.py run-python install-user  `

**Comment by nikohansen** [comment]
Thanks for the notice! A code inspection suggests that `install-user` and `--user` do exactly the same, so I don't have a conclusive explanation to why all this happened.
