### ISSUE TITLE
[Bug report] Fatal error when creating a filtered suite with no functions

### ISSUE THREAD

**Issue by olafmersmann** [numbbo/coco#2181]
The following simple program raises a fatal error when creating a suite with no functions.
It really should just return an empty suite.

```c
#include "coco.h"


int main(void) {
  coco_suite_t *suite = coco_suite("bbob", "", "dimensions:4");

  return 0;
}
```

**Comment by olafmersmann** [comment]
Here's a backtrace:
```
#0  coco_error (message=0x4cee00 "coco_suite_is_next_item_found(): the chosen suite has no valid (positive) items")
    at coco_runtime_c.c:19
#1  0x0000000000427d1b in coco_suite_is_next_item_found (items=0x4fa340, number_of_items=6, current_item_id=0x4fa2e8)
    at coco_suite.c:539
#2  0x0000000000427dd7 in coco_suite_is_next_dimension_found (suite=0x4fa2a0) at coco_suite.c:587
#3  0x000000000042848c in coco_suite (suite_name=0x43203e "bbob", suite_instance=0x43203d "", suite_options=0x432030 "dimensions:4")
    at coco_suite.c:796
#4  0x0000000000402442 in main () at buggy-mcbug.c:5
```

**Comment by nikohansen** [comment]
It doesn't quite look like a bug but rather like a too cryptic user value error message?

**Comment by olafmersmann** [comment]
It's a bit overzealous to exit the process because you tried to instantiate a suite with no functions. I changed it to raise an exception in Python.
