### ISSUE TITLE
ValueError while running an experiment

### ISSUE THREAD

**Issue by agissler** [numbbo/coco#2188]
When I run an experiment in Pyzo ([Python v3.9.13, conda]), I got this error

`ValueError: could not convert string to float: '1,8e-03'`

This does not happen when I use VisualStudio with the same computer and the same version of Python.

I precise that my computer is using Ubuntu 22.04.2 LTS and is configured in French. I used version v.2.6.2 of coco.

**Comment by nikohansen** [comment]
Could you please provide the full error message?

I also suspect the error is not raised while running the experiment, right?

**Comment by agissler** [comment]
No it is only showing in the end of the experiment

Traceback (most recent call last):
  File "[path]/example_experiment2_lq_cma.py", line 249, in <module>
    cocopp.main(observer.result_folder)  # re-run folders look like "...-001" etc
  File "[path]/anaconda3/lib/python3.9/site-packages/cocopp/rungeneric.py", line 408, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
  File "[path]/anaconda3/lib/python3.9/site-packages/cocopp/rungeneric1.py", line 72, in main
    dsList = DataSetList(alg)
  File "[path]anaconda3/lib/python3.9/site-packages/cocopp/pproc.py", line 2146, in __init__
    self.processIndexFile(name, alg_name)
  File "[path]anaconda3/lib/python3.9/site-packages/cocopp/pproc.py", line 2236, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)
  File "[path]/anaconda3/lib/python3.9/site-packages/cocopp/pproc.py", line 871, in __init__
    self.readfinalFminusFtarget.append(float(readfinalf))
ValueError: could not convert string to float: '1,5e+01'

**Comment by nikohansen** [comment]
These are the code lines from `coco.pproc` that fail in the end:
```python
                    itrial, info = elem.split(':', 1)
                       .
                       .
                       .
                    readmaxevals, readfinalf = info.split('|', 1)
                    self.readmaxevals.append(int(readmaxevals))
                    self.readfinalFminusFtarget.append(float(readfinalf))
```

Is the C code in need to control the language setting to prevent writing decimal points as commata?

**Comment by nikohansen** [comment]
Loosely related: #2025
