### ISSUE TITLE
Installation should work even without git

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#2259]
Right now, installing `cocoex` in the development branch assumes the repository was cloned with git. If this is not the case, it fails with the following error:

```
(coco) C:\Users\Tea\Downloads\coco-development>python scripts/fabricate
Traceback (most recent call last):
  File "C:\Users\Tea\Downloads\coco-development\scripts\fabricate", line 232, in <module>
    COCO_VERSION = git_version()
                   ^^^^^^^^^^^^^
  File "C:\Users\Tea\Downloads\coco-development\scripts\fabricate", line 140, in git_version
    res = git(['describe', '--tags']).lstrip("v").split("-")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tea\Downloads\coco-development\scripts\fabricate", line 128, in git
    output = subprocess.check_output(full_command,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tea\anaconda3\envs\coco\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tea\anaconda3\envs\coco\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```

**Comment by olafmersmann** [comment]
Added a simple fix to the `development` branch. Maybe we should also output some warning since it's a not actively tested build setup?
