### ISSUE TITLE
Bbob Noisy test suite issue in Bbobbenchmarks.py

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2265]
I am running bayesian optimization on the bbob noisy suite and I am getting this error:
```
Traceback (most recent call last):
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/NoisyBayOpt.py", line 147, in <module>
    train_x,train_y, mean_gp, variance_gp, acquisition_values_ei, model = Bayopt(f.evalfun, dim,  (eval(maxfunevals) - f.        evaluations),2,'EI')
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/NoisyBayOpt.py", line 70, in Bayopt
    y = fun(x)
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/fgeneric.py", line 264, in evalfun
    out = self._fun_evalfull( x, *args, **kwargs )
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/bbobbenchmarks.py", line 637, in _evalfull
    fval = self.noise(ftrue)
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/bbobbenchmarks.py", line 558, in noise
    return fGauss(ftrue, self.gaussbeta)
  File "/Users/yash.pisat/Desktop/COCO OLD/bbob.v15.03/python/bbobbenchmarks.py", line 302, in fGauss
    fval[idx] = ftrue[idx]
TypeError: 'numpy.float64' object does not support item assignment 
```

**Comment by nikohansen** [comment]
You are using somewhat outdated code? In my code I see this
```python
def fGauss(ftrue, beta):
    """Returns Gaussian model noisy value."""
    # expects ftrue to be a np.array
    popsi = np.shape(ftrue)
    fval = ftrue * np.exp(beta * _randn(popsi)) # with gauss noise
    tol = 1e-8
    fval = fval + 1.01 * tol
    idx = ftrue < tol
    try:
        fval[idx] = ftrue[idx]
    except (IndexError, TypeError): # fval is a scalar
        if idx:
            fval = ftrue
    return fval
```
which should fix your error. This is (must be) done for all three noise models.

**Comment by Yash-Pisat** [comment]
Thanks for the quick response.

I am using the code which is downloaded from this link:
![image](https://github.com/numbbo/coco/assets/111347181/4f0cf432-2618-4e72-9bde-df230019f347)

This is the code that I am using:
```
def fGauss(ftrue, beta):
    """Returns Gaussian model noisy value."""
    # expects ftrue to be a np.array
    popsi = np.shape(ftrue)
    fval = ftrue * np.exp(beta * _randn(popsi)) # with gauss noise
    tol = 1e-8
    fval = fval + 1.01 * tol
    idx = ftrue < tol
    try:
        fval[idx] = ftrue[idx]
    except IndexError: # fval is a scalar
        if idx:
            fval = ftrue
    return fval

```
Also one more request, can you direct me where I can find the updated code.

**Comment by Yash-Pisat** [comment]
Thankyou, I changed a bit of code since I was not able to find the updated code. It worked, thankyou.

**Comment by nikohansen** [comment]
For the record, one way to get the code is, after installing the `cma` Python package with ``pip install cma``:
```python
from cma import bbobbenchmarks as bbob
```
