### ISSUE TITLE
Getting error in pprldmany.py when running experiments with 2 functions in a custom suite

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2267]
I created a custom suite with one function in it and ran the experiment it worked perfectly after integrating it with the coco framework. Now I added one more function to the same suite and made the necessary changes but I am getting this error which I am not able to debug.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yash.pisat/Desktop/Thesis/coco/venv/lib/python3.11/site-packages/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/Desktop/Thesis/coco/venv/lib/python3.11/site-packages/cocopp/rungeneric.py", line 408, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/Desktop/Thesis/coco/venv/lib/python3.11/site-packages/cocopp/rungeneric1.py", line 222, in main
    pprldmany.all_single_functions(dictAlg,
  File "/Users/yash.pisat/Desktop/Thesis/coco/venv/lib/python3.11/site-packages/cocopp/compall/pprldmany.py", line 524, in all_single_functions
    main(tempDictAlg,
  File "/Users/yash.pisat/Desktop/Thesis/coco/venv/lib/python3.11/site-packages/cocopp/compall/pprldmany.py", line 950, in main
    testbedsettings.current_testbed.short_names[list(dictFunc.keys())[0]])),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 2

**Comment by nikohansen** [comment]
Are you sure you updated the information for the testbed according to the changes? It seems like the `shortinfo_filename` in testbed class which is defined in `cocopp.testbedsettings` (and is by default `'bbob-benchmarkshortinfos.txt'`) does not have enough entries.
