### ISSUE TITLE
No module named 'cocoex'

### ISSUE THREAD

**Issue by TELO-anonym** [numbbo/coco#2283]
I faced an error installing the cocoex when I tried step 3 in the [link](https://github.com/numbbo/coco?tab=readme-ov-file#getting-started-). How can I fix this?

 python do.py run-python
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build/python/cython/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/python/bbob2009_testcases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install in code-experiments\build\python

An exception occurred while trying to install packages.

A common reason for this error is insufficient access rights
to the installation directory. The original exception message
is as follows:

/----------------------------< EXCEPTION MESSAGE >----------------------------\
|                                                                             |
| NOTE: Using precompiled C file to build interface.                          |
| Traceback (most recent call last):                                          |
|   File "setup.py", line 48, in <module>                                     |
|     setup(                                                                  |
|   File "D:\Users\64863\anaconda3\envs\boea\lib\site-packages\setuptools\_di |
| stutils\core.py", line 147, in setup                                        |
|     _setup_distribution = dist = klass(attrs)                               |
|   File "D:\Users\64863\anaconda3\envs\boea\lib\site-packages\setuptools\dis |
| t.py", line 314, in __init__                                                |
|     self.metadata.version = self._normalize_version(self.metadata.version)  |
|   File "D:\Users\64863\anaconda3\envs\boea\lib\site-packages\setuptools\dis |
| t.py", line 350, in _normalize_version                                      |
|     normalized = str(Version(version))                                      |
|   File "D:\Users\64863\anaconda3\envs\boea\lib\site-packages\setuptools\_ve |
| ndor\packaging\version.py", line 198, in __init__                           |
|     raise InvalidVersion(f"Invalid version: '{version}'")                   |
| setuptools.extern.packaging.version.InvalidVersion: Invalid version: ''     |
\-----------------------------------------------------------------------------/

To fix an access rights issue, you may try the following:

- Run the same command with "install-user" as additional argument.
  To get further help run do.py without a specific command.

- On *nix systems or MacOS, run the same command with a preceded "sudo ".

- Gain write access to the installation directory by changing
  access permissions or gaining administrative access.

PYTHON  example_experiment.py bbob in code-experiments\build\python
ERROR: return value=1
Traceback (most recent call last):
  File "example_experiment.py", line 46, in <module>
    import cocoex
ModuleNotFoundError: No module named 'cocoex'

**Comment by nikohansen** [comment]
I have not seen this before. I am not sure at all, but a quick fix may be to downgrade `setuptools` to version < 66 like

```sh
pip install --upgrade setuptools==65 
```

**Comment by nikohansen** [comment]
Is this problem been solved?

**Comment by nikohansen** [comment]
Thanks, excellent, are you comfortable sharing the resolution you found?

**Comment by TELO-anonym** [comment]
According to your suggestions, I have fixed this by downgrading the ``setuptools'' and the Python version.
