### ISSUE TITLE
Changing captions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2292]
I am changing some caption in `compall/tables.py`. I suspect that this change is not effective unless some `preparation` code is run? I fail to find the recipe how to do this. If this is necessary, it should also be listed the in [`howtos/release-howto.md`](https://github.com/numbbo/coco/blob/development/howtos/release-howto.md)?

**Comment by nikohansen** [comment]
Apart from the backslash, the above doesn't work for me because my `code-postprocessing` folder does not contain the file `preparehtml.py`. When I run

```sh
python cocopp/preparehtml.py  
```
I get this error
```
pdflatex done
Traceback (most recent call last):
  File "/Users/hansen/git/coco/code-postprocessing/cocopp/preparehtml.py", line 86, in <module>
    main(args)
  File "/Users/hansen/git/coco/code-postprocessing/cocopp/preparehtml.py", line 24, in main
    prepare_html(texFile)
  File "/Users/hansen/git/coco/code-postprocessing/cocopp/preparehtml.py", line 46, in prepare_html
    subprocess.call(args.split(), stdout=FNULL, stderr=FNULL, shell=False)    
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hansen/opt/anaconda3/envs/coco/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hansen/opt/anaconda3/envs/coco/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/hansen/opt/anaconda3/envs/coco/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/hansen/git/coco/code-postprocessing/cocopp/tth_C/tth'
```

**Comment by nikohansen** [comment]
```sh
brew install tth
```
installs tth on the Mac. After changing the `preparehtml.py` file accordingly (commit fc3a88fe6a), I could run
```python
python cocopp/preparehtml.py
```
and see changes in `cocopp/latex_commands_for_html.html`

**Comment by nikohansen** [comment]
# How make caption changes effective

0) MacOS only:
```sh
brew install tth
```
1)
```sh
cd code-postprocessing
python cocopp/preparehtml.py  
```
2) The changes are now in `cocopp/latex_commands_for_html.html` and must be committed.
