### ISSUE TITLE
Python crashes under Ubuntu Linux

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#317]
On Tobias' linux machine, build-python does not work:

```
twagner@TR30:~/numbbo$ python do.py build-python
AML     ['code-experiments/src/coco_generics.c', 'code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
COPY    code-experiments/src/coco.h -> code-experiments/build/python/cython/coco.h
COPY    code-experiments/src/best_values_hyp.txt -> code-experiments/build/python/best_values_hyp.txt
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/python/bbob2009_testcases.txt
EXPAND  code-experiments/build/python/README.in to code-experiments/build/python/README
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/python/setup.py
PYTHON  setup.py install --user in code-experiments/build/python
ERROR: return value=1
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import setuptools
ImportError: No module named setuptools
Traceback (most recent call last):
  File "do.py", line 562, in <module>
    main(sys.argv[1:])
  File "do.py", line 539, in main
    elif cmd == 'build-python': build_python()
  File "do.py", line 203, in build_python
    python('code-experiments/build/python', ['setup.py', 'install', '--user'])
  File "/vol2/twagner/numbbo/code-experiments/tools/cocoutils.py", line 92, in python
    universal_newlines=True)
  File "/usr/local/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', 'setup.py', 'install', '--user']' returned non-zero exit status 1
```

**Comment by nikohansen** [comment]
I added this "known" issue to the `README.md` Trouble-Shooting section. We will see what Tobias reports back before to close this issue.
