### ISSUE TITLE
postprocessing test fails

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#335]
On my Mac OSX 10.9.5
```
[20:02:21] 1 code-postprocessing$ python bbob_pproc/
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Convergence plots done.
Scaling figures... Loading best algorithm data from BBOB-2009...   done (Sat Jan 16 20:02:50 2016).
  done (Sat Jan 16 20:03:06 2016).
TeX tables...   done (Sat Jan 16 20:03:06 2016).
ECDF graphs...   done (Sat Jan 16 20:03:17 2016).
ERT loss ratio figures and tables...   done (Sat Jan 16 20:03:21 2016).
Output data written to folder ppdata/BFGS_ros_noiseless
  done (Sat Jan 16 20:03:21 2016).
('**  subtest 1 finished in ', 56.861250162124634, ' seconds')
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/git/numbbo/code-postprocessing/bbob_pproc/__main__.py", line 233, in <module>
    main(sys.argv[1:])
  File "/Users/hansen/git/numbbo/code-postprocessing/bbob_pproc/__main__.py", line 141, in main
    assert not result, 'Test failed: error while generating pdf from templateBBOBarticle.tex.'
AssertionError: Test failed: error while generating pdf from templateBBOBarticle.tex.
```

**Comment by dtusar** [comment]
Yes, it's interesting. If you call it this way it fails but from do.py it goes through.

**Comment by nikohansen** [comment]
Some LaTeX related problem?

**Comment by dtusar** [comment]
Probably, it fails during the pdflatex call. Maybe is related to the path to the files needed in the LaTeX file.

**Comment by dtusar** [comment]
@nikohansen Now that the post-processing is called as a module is this still an issue?

**Comment by brockho** [comment]
@nikohansen: would you be so kind and check whether this issue is still open?

**Comment by nikohansen** [comment]
```
[17:41:00] 0 ~$ python -m bbob_pproc --test
preparing algorithm data
Traceback (most recent call last):
  File "/Users/hansen/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3-py2.7.egg/bbob_pproc/__main__.py", line 334, in <module>
    main(args)  # is not likely to work
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3-py2.7.egg/bbob_pproc/__main__.py", line 186, in main
    copy_latex_templates()
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3-py2.7.egg/bbob_pproc/__main__.py", line 72, in copy_latex_templates
    shutil.copy(join_path(templateFolder, 'bbob.bib'), currentFolder)
  File "/Users/hansen/anaconda2/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/Users/hansen/anaconda2/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3-py2.7.egg/latex-templates/bbob.bib'
[17:41:17] 0 ~$ 
```

**Comment by brockho** [comment]
I have an idea of where the problem might come from: the BibTeX file seems not being included in the postprocessing installation. I will have a closer look whether this solves the issue.

**Comment by nikohansen** [comment]
this fixed it.

**Comment by nikohansen** [comment]
back again, see #1002

**Comment by nikohansen** [comment]
For the time being considered as won't fix.
