### ISSUE TITLE
error during postprocessing when inf is in the data

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#371]
We might want the post-processing to be robust to these kind of data. 
```
[10:49:17] 0 Downloads$ python -m bbob_pproc --svg CMAES_2MEAN
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/CMAES_2MEAN
  this might take several minutes.
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/__main__.py", line 38, in <module>
    cocopp.rungeneric.main(args)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/rungeneric.py", line 264, in main
    + ["-o", outputdir, alg])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/rungeneric1.py", line 292, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/pproc.py", line 1400, in __init__
    self.processIndexFile(name, verbose)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/pproc.py", line 1472, in processIndexFile
    verbose))
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/pproc.py", line 776, in __init__
    data = VMultiReader(split(dataFiles), self.isBiobjective())
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.0.6134-py2.7.egg/bbob_pproc/readalign.py", line 390, in split
    data[id] = float(data[id])
ValueError: invalid literal for float(): +1.#INF00000e+000
```
Data attached. 
[cmaes_2mean.zip](https://github.com/numbbo/coco/files/94322/cmaes_2mean.zip)

**Comment by nadya-p** [comment]
I can't reproduce the issue on my Windows7, x64 machine using python 2.7.12 (Anaconda2).

1. First, the option --svg doesn't appear to exist:
```
C:\work>C:\Anaconda2\python.exe -m bbob_pproc --svg cmaes_2mean
option --svg not recognized
```
I guess it was replaced by --no-svg, which is inactive by default.

2. I observe a UserWarning, not a ValueError. I guess the error was already fixed. @brockho, if it is indeed the case, could you please close the issue?
