### ISSUE TITLE
post-processing key error

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#408]
I still have this problem:
```
[15:28:30] 0 coco$ python -m bbob_pproc random_search_on_bbob-biobj/
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/random_search_on_bbob-biobj
  this might take several minutes.
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/pproc.py:814: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/pproc.py:905: UserWarning:   less than 15 instances in [1, 2, 3, 4, 5] (f1, 2D)
  str(self.dim) + 'D)')
Using bestGECCO2009 based target values: now for each function the target values differ, but the "level of difficulty" is "the same". 
Scaling figures... Loading best bi-objective algorithm data from BBOB-2016...   done (Tue Jan 19 15:28:35 2016).
Loading best bi-objective algorithm data from BBOB-2016...   done (Tue Jan 19 15:28:35 2016).
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/__main__.py", line 275, in <module>
    rungeneric.main(args)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/rungeneric.py", line 264, in main
    + ["-o", outputdir, alg])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/rungeneric1.py", line 354, in main
    outputdir, genericsettings.verbose)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/ppfigdim.py", line 528, in main
    plot(dictFunc[func], _valuesOfInterest, styles=styles)  # styles might have changed via config
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/ppfigdim.py", line 362, in plot
    tmp = generateData(dictFunc[func][dim][0], valuesOfInterest((func, dim))[i_target])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-test.from-py2.7.egg/bbob_pproc/pproc.py", line 340, in __call__
    ds = self.reference_data[dim_fun]
KeyError: (40, 1)
```

**Comment by dtusar** [comment]
Dimo, can you please change the bestbiobjalgentries2016.pickle.gz with one which has also 40-D data.

**Comment by brockho** [comment]
should be solved now with the new bestalg pickle file

**Comment by nikohansen** [comment]
looks like I have a different key error now:
```
[21:32:29] 0 coco$ python -m bbob_pproc random_search_on_bbob-biobj/
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/random_search_on_bbob-biobj
  this might take several minutes.
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/pproc.py:814: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/pproc.py:905: UserWarning:   less than 15 instances in [1, 2, 3, 4, 5] (f1, 2D)
  str(self.dim) + 'D)')
Using bestGECCO2009 based target values: now for each function the target values differ, but the "level of difficulty" is "the same". 
Scaling figures... Loading best bi-objective algorithm data from BBOB-2016...   done (Wed Jan 20 21:32:31 2016).
Loading best bi-objective algorithm data from BBOB-2016...   done (Wed Jan 20 21:32:31 2016).
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/__main__.py", line 283, in <module>
    rungeneric.main(args)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/rungeneric.py", line 278, in main
    + ["-o", outputdir, alg])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/rungeneric1.py", line 354, in main
    outputdir, genericsettings.verbose)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/ppfigdim.py", line 528, in main
    plot(dictFunc[func], _valuesOfInterest, styles=styles)  # styles might have changed via config
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/ppfigdim.py", line 362, in plot
    tmp = generateData(dictFunc[func][dim][0], valuesOfInterest((func, dim))[i_target])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.2a0-py2.7.egg/bbob_pproc/pproc.py", line 340, in __call__
    ds = self.reference_data[dim_fun]
KeyError: (2, 1)
```

**Comment by brockho** [comment]
I will have a look.

**Comment by brockho** [comment]
I can reproduce the bug with a newly run random search data folder (run through example_experiment.c). However, I don't get any KeyError when postprocessing the SMS-EMOA output which I used to create the `code-postprocessing/bbob_pproc/bestbiobjalgentries2016.pickle.gz` file. This is actually the reason why I pushed the code originally.

Have to dig further into the postprocessing tomorrow to see where the bug is actually caused. However, I also here get more `Loading best bi-objective algorithm data from BBOB-2016...   done` than I would expect (question: shall I file already a new issue for this?).

**Comment by nikohansen** [comment]
Cool label :-) 
The bug looks pretty strange to me. No idea, maybe tomorrow...

**Comment by brockho** [comment]
I thought that because the experiment is so short, some runs might not even hit a single target (i.e. the .dat file is empty for some instance, but this cannot be because we always write the first evaluation, right?

**Comment by nikohansen** [comment]
Right, this should not be, but could yet be the reason for the bug. Not sure how the easiest target is chosen at the moment, it should be `inf`.

**Comment by dtusar** [comment]
The problem is in the bestbiobjalgentries2016.pickle.gz file. I didn't check what is inside it but in 61 Bytes it cannot be much.

**Comment by brockho** [comment]
`bestalg.customgenerate(...)` now also gives the following type of warning for every function and dimension if I want to read in `bbob-biobj` data folders which definitely have all dimensions and functions in both `.dat` and `.info` files. This did not happen before, I guess:
```
bbob_pproc\bestalg.py:127: UserWarning: Algorithm ../code-experiments/build/c/RS
_on_bbob-004/ was not tested on f55 40-D.
```
Seems to be the reason for the very small bestbiobjalgentries2016.pickle.gz file. I will investigate it further.

**Comment by brockho** [comment]
Okay, the bestbiobjalgentries2016.pickle.gz is updated now. It was my mistake when calling the customgenerate method (I used square brackets around the algorithm data folders instead of normal brackets). Nevertheless, I now get a completely different error, when running the postprocessing:
```
C:\Users\dimo\Desktop\coco\BBOB\workshops\2016-biobj\prelimDataFromUs>python -m
bbob_pproc SMSEMOA_on_bbob-biobj-1e3DIMfunevals
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata\SMSEMOA_on_bbob-
biobj-1e3DIMfunevals
  this might take several minutes.
C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0.0.6370-
py2.7.egg\bbob_pproc\pproc.py:905: UserWarning:   less than 15 instances in [1,
2, 3, 4, 5, 6, 7, 8, 9, 10] (f1, 2D)
  str(self.dim) + 'D)')
Scaling figures... Loading best bi-objective algorithm data from BBOB-2016...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\__main__.py", line 283, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\rungeneric.py", line 278, in main
    + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\rungeneric1.py", line 354, in main
    outputdir, genericsettings.verbose)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\ppfigdim.py", line 516, in main
    bestalg.loadBestAlgorithm(dsList.isBiobjective())
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\bestalg.py", line 481, in loadBestAlgorithm
    loadBestBiobj2016()
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.6370-py2.7.egg\bbob_pproc\bestalg.py", line 472, in loadBestBiobj2016
    bestbiobjalgentries2016 = pickle.load(fid)
  File "C:\Users\dimo\Anaconda\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Users\dimo\Anaconda\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Users\dimo\Anaconda\lib\pickle.py", line 1069, in load_inst
    klass = self.find_class(module, name)
  File "C:\Users\dimo\Anaconda\lib\pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named bestalg
```
@nikohansen: Can it have something to do with the installation of the bbob_pproc package?

**Comment by nikohansen** [comment]
Yes, and/or with the question of relative vs absolute imports. Maybe an `from . import bestalg` before loading might help?

**Comment by nikohansen** [comment]
Closing this, because it seems now covered by #56. On the long run we want to migrate the pickle files to new class objects or get rid of them.
