### ISSUE TITLE
post-processing fails on CI

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#414]
There is an error apparently related to `tkagg` and therefore the `matplotlib` backend settings, which I cannot reproduce locally and I am not sure how this problem has been introduced. 

```
+ python do.py test-post-processing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install --user in code-postprocessing
PYTHON	__main__.py in code-postprocessing/bbob_pproc
ERROR: return value=1
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/builds/.local/lib/python2.7/site-packages/bbob_pproc-v0.2.alpha-py2.7.egg/bbob_pproc/__main__.py", line 281, in <module>
    rungeneric.main(args)
  File "/builds/.local/lib/python2.7/site-packages/bbob_pproc-v0.2.alpha-py2.7.egg/bbob_pproc/rungeneric.py", line 276, in main
    + ["-o", outputdir, alg])
  File "/builds/.local/lib/python2.7/site-packages/bbob_pproc-v0.2.alpha-py2.7.egg/bbob_pproc/rungeneric1.py", line 341, in main
    ppconverrorbars.main(dictAlg, outputdir, genericsettings.verbose)
  File "/builds/.local/lib/python2.7/site-packages/bbob_pproc-v0.2.alpha-py2.7.egg/bbob_pproc/ppconverrorbars.py", line 76, in main
    plt.figure()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 343, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 80, in new_figure_manager
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1688, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
WARNING: this tests the post-processing, this might change in future (use -h for help)
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
python -m  bbob_pproc --conv /builds/disk/workspace/Coco-experiments-test3-linux/dotype/test-post-processing/label/numbbo-ubuntu-12p04-i386/code-postprocessing/bbob_pproc/data/BFGS_ros_noiseless.tgz
('**  subtest 1 finished in ', 11.835223197937012, ' seconds')
Traceback (most recent call last):
  File "__main__.py", line 271, in <module>
    main(args)
  File "__main__.py", line 162, in main
    assert result == 0, 'Test failed: rungeneric on one algorithm with option --conv.'
AssertionError: Test failed: rungeneric on one algorithm with option --conv.

Traceback (most recent call last):
  File "do.py", line 621, in <module>
    main(sys.argv[1:])
  File "do.py", line 615, in main
    elif cmd == 'test-post-processing': test_post_processing()
  File "do.py", line 503, in test_post_processing
    python('code-postprocessing/bbob_pproc', ['__main__.py'])
  File "/builds/disk/workspace/Coco-experiments-test3-linux/dotype/test-post-processing/label/numbbo-ubuntu-12p04-i386/code-experiments/tools/cocoutils.py", line 123, in python
    universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '__main__.py']' returned non-zero exit status 1
```

**Comment by nikohansen** [comment]
I believe the problem is the test call (it's done with `python -m` now), the problem is not a new bug in the post-processing code.

**Comment by dtusar** [comment]
On the CI linux slave I used the ipython console and tried this: import bbob_pproc. I got this message:
/usr/lib/pymodules/python2.7/matplotlib/__init__.py:923: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

**Comment by nikohansen** [comment]
Right, `matplotlib.use('Agg')` is all over the place in the code. It shouldn't do any harm though.

**Comment by dtusar** [comment]
Yes, but maybe is still missing somewhere before the pylab or matplotlib.pyplot call. I don't know, just guessing.

**Comment by nikohansen** [comment]
OK, good point, so I will put in in `__init__` and `__main__`, that should guaranty that it is called.

**Comment by nikohansen** [comment]
Excellent, that did the trick!
