### ISSUE TITLE
run-octave crashed on Windows slave

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#488]
The new run-octave in my own fork crashed on our Windows slave. The error, we get is the following:
```
Started by upstream project "Coco-experiments-windows-dimo" build number 8
originally caused by:
 Started by user dimos@email.fr
Building remotely on numbbo-win32bitwithjre in workspace C:\builds\workspace\Coco-experiments-windows-dimo\dotype\run-octave\label\numbbo-win32bitwithjre
Cloning the remote Git repository
Cloning repository https://github.com/brockho/numbbo/
 > git init C:\builds\workspace\Coco-experiments-windows-dimo\dotype\run-octave\label\numbbo-win32bitwithjre # timeout=10
Fetching upstream changes from https://github.com/brockho/numbbo/
 > git --version # timeout=10
using GIT_SSH to set credentials 
using .gitcredentials to set credentials
 > git config --local credential.username NumbboCI # timeout=10
 > git config --local credential.helper store --file=\"C:\Users\ci\AppData\Local\Temp\git3475996442847393362.credentials\" # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/brockho/numbbo/ +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/brockho/numbbo/ # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/brockho/numbbo/ # timeout=10
Fetching upstream changes from https://github.com/brockho/numbbo/
using GIT_SSH to set credentials 
using .gitcredentials to set credentials
 > git config --local credential.username NumbboCI # timeout=10
 > git config --local credential.helper store --file=\"C:\Users\ci\AppData\Local\Temp\git4833232904249941020.credentials\" # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/brockho/numbbo/ +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
Checking out Revision d7e5df4b9ee54edff902bef6b6972c9a7d820942 (refs/remotes/origin/dimo-doctesting)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d7e5df4b9ee54edff902bef6b6972c9a7d820942
First time build. Skipping changelog.
[numbbo-win32bitwithjre] $ cmd /c call C:\Users\ci\AppData\Local\Temp\hudson765000754274621937.bat

C:\builds\workspace\Coco-experiments-windows-dimo\dotype\run-octave\label\numbbo-win32bitwithjre>python do.py run-octave 
CLEAN	 mex files from code-experiments/build/matlab/
AML	['code-experiments/src/coco_generics.c', 'code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/matlab/coco.c
COPY	code-experiments/src/coco.h -> code-experiments/build/matlab/coco.h
WRITE	code-experiments/build/matlab/REVISION
WRITE	code-experiments/build/matlab/VERSION
RUN	octave --no-gui setup.m in code-experiments/build/matlab
RUN	octave --no-gui exampleexperiment.m in code-experiments/build/matlab
ERROR: return value=1
error: 'cocoSuite' undefined near line 21 column 9
error: called from
    exampleexperiment.m at line 21 column 7

Traceback (most recent call last):
  File "do.py", line 638, in <module>
    main(sys.argv[1:])
  File "do.py", line 621, in main
    elif cmd == 'run-octave': run_octave()    
  File "do.py", line 411, in run_octave
    run('code-experiments/build/matlab', ['octave', '--no-gui', 'exampleexperiment.m'])
  File "C:\builds\workspace\Coco-experiments-windows-dimo\dotype\run-octave\label\numbbo-win32bitwithjre\code-experiments\tools\cocoutils.py", line 103, in run
    universal_newlines=True)
  File "C:\Anaconda\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['octave', '--no-gui', 'exampleexperiment.m']' returned non-zero exit status 1

C:\builds\workspace\Coco-experiments-windows-dimo\dotype\run-octave\label\numbbo-win32bitwithjre>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Sending e-mails to: dimos@email.fr
Finished: FAILURE
```

**Comment by brockho** [comment]
Probably, the Cygwin gcc is causing the problem here. Changing to MinGW's gcc, however, needs the other Windows slave back.

**Comment by brockho** [comment]
Done by Dejan by installing a new Windows slave with the right installation as documented.
