### ISSUE TITLE
ECDFs of single functions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#495]
The option 
```
python -m bbob_pproc --rld-single-fcts folder_name
```

seems to be broken. I tried with several different data set. 

```python
[15:10:03] 0 python$ python -m bbob_pproc --rld-single-fcts ../../../random_search_on_bbob2009/
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/random_search_on_bbob2009
  this might take several minutes.
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/pproc.py:814: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/pproc.py:1045: UserWarning: 5:22|3.5e+02funcId is an additional attribute.
  warnings.warn('%s is an additional attribute.' % (attrname))
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/pproc.py:1463: UserWarning: Entry in file ./../../../random_search_on_bbob2009/bbobexp_f1_i1.info at line 19 is faulty: it will be skipped.
  'it will be skipped.')
/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/pproc.py:899: UserWarning:   double instances in [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4] (f1, 2D)
  + 'D)')
Using bestGECCO2009 based target values: now for each function the target values differ, but the "level of difficulty" is "the same". 
Scaling figures... Loading best algorithm data from BBOB-2009...   done (Mon Jan 25 15:10:40 2016).
  done (Mon Jan 25 15:10:51 2016).
TeX tables...   done (Mon Jan 25 15:10:51 2016).
ECDF graphs...
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/__main__.py", line 283, in <module>
    rungeneric.main(args)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/rungeneric.py", line 278, in main
    + ["-o", outputdir, alg])
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/rungeneric1.py", line 410, in main
    genericsettings.verbose)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b2-py2.7.egg/bbob_pproc/compall/pprldmany.py", line 456, in all_single_functions
    verbose=verbose)
TypeError: main() takes at least 2 arguments (5 given)
```

**Comment by dtusar** [comment]
Fixed.
