### ISSUE TITLE
post-processing test fails without do.py

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#518]
This is problem persists already for some time, but should be resolved at some point: the test of the post-processing from the command shell fails. It runs through only when using `do.py`.
```
$ python code-postprocessing/bbob_pproc
WARNING: this tests the post-processing, this might change in future (use -h for help)
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
python -m  bbob_pproc --conv /Users/hansen/git/coco/code-postprocessing/bbob_pproc/data/BFGS_ros_noiseless.tgz
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Convergence plots done.
Scaling figures... Loading best algorithm data from BBOB-2009...   done (Wed Jan 27 10:29:44 2016).
  done (Wed Jan 27 10:29:59 2016).
TeX tables...   done (Wed Jan 27 10:30:00 2016).
ECDF graphs...   done (Wed Jan 27 10:30:11 2016).
ERT loss ratio figures and tables...   done (Wed Jan 27 10:30:15 2016).
Output data written to folder ppdata/BFGS_ros_noiseless
  done (Wed Jan 27 10:30:15 2016).
('**  subtest 1 finished in ', 57.681121826171875, ' seconds')
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/git/coco/code-postprocessing/bbob_pproc/__main__.py", line 273, in <module>
    main(args)
  File "/Users/hansen/git/coco/code-postprocessing/bbob_pproc/__main__.py", line 167, in main
    assert not result, 'Test failed: error while generating pdf from templateBBOBarticle.tex.'
AssertionError: Test failed: error while generating pdf from templateBBOBarticle.tex.
```

Testing the installed module fails even earlier: 
```
[10:30:15] 0 coco$ python -m bbob_pproc -t
preparing algorithm data
Traceback (most recent call last):
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b3-py2.7.egg/bbob_pproc/__main__.py", line 276, in <module>
    main(args)  # is not likely to work
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b3-py2.7.egg/bbob_pproc/__main__.py", line 150, in main
    data_path = ' ' + prepare_data(run_all_tests)
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b3-py2.7.egg/bbob_pproc/__main__.py", line 83, in prepare_data
    retrieve_algorithm(dataPath, '2009', 'BFGS_ros_noiseless.tgz')    
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b3-py2.7.egg/bbob_pproc/__main__.py", line 73, in retrieve_algorithm
    urllib.urlretrieve(dataurl, algorithmFile)
  File "/Users/hansen/anaconda/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/Users/hansen/anaconda/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: '/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-0.5b3-py2.7.egg/bbob_pproc/data/BFGS_ros_noiseless.tgz'
```

**Comment by dtusar** [comment]
I noticed this yesterday. Regarding the error when testing the installed module we need to add to the installation the data folder (with the two sub folders) and the latex-templates folder in order to successfully run the tests.

**Comment by dtusar** [comment]
For running from command shell is almost fixed. Only one error left in doctests.

**Comment by markuswagnergithub** [comment]
Maybe related or totally new issue:
`templateBBOBarticle.tex` wants to include files like `pprldistr_05D_separ`, but that is never generated. I do have other files `pprldistr_05D_*`, though, like `pprldistr_05D_1-separable_1-separable.pdf`.

**Comment by dtusar** [comment]
Now all the tests in `doctest `are fixed. 

@nikohansen please add to the installation also copying the `latex-templates` folder and `data` folder (with two sub folders). Then you can close this issue.

**Comment by nikohansen** [comment]
This needs to be done in `code-postprocessing/setup.py.in`, around line 20.

I added `latex-templates/*`, but I don't know which data files need to be added. I also don't know exactly how to guaranty that a folder structure is copied (there is a link to [this doc](https://docs.python.org/2/distutils/setupscript.html) in the code), though it seemed to work for the `js` and `tth` folder.

**Comment by dtusar** [comment]
Updated also `code-postprocessing/setup.py.in`.
