### ISSUE TITLE
bbop_pproc fails with assertion

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#582]
Hi, I tried to follow the C install procedure outlined in the readme. However when trying to use the post-processing after running the example experiment, i run into an assertion:

```
python2.7 -m bbob_pproc  exdata/
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/exdata
  this might take several minutes.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/__main__.py", line 287, in <module>
    rungeneric.main(args)
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/rungeneric.py", line 278, in main
    + ["-o", outputdir, alg])
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/rungeneric1.py", line 292, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/pproc.py", line 1434, in __init__
    self.processIndexFile(name, verbose)
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/pproc.py", line 1506, in processIndexFile
    verbose))
  File "/home/ulfi/.local/lib/python2.7/site-packages/bbob_pproc-0.7b1-py2.7.egg/bbob_pproc/pproc.py", line 828, in __init__
    assert all(self.evals[0][1:] == 1)        
AssertionError
```

Any idea? The assertion is unfortunately not very helpful for me.

**Comment by ttusar** [comment]
Thanks for reporting this issue. The assertion fails because the first target value is not always hit. We are currently working on this, but it's not fixed yet. For the time being you can safely comment/delete this line. We will let you know when this issue is solved.

**Comment by ttusar** [comment]
This has now been solved. You can find the correction in the development branch. It will be included in the next release (the issue will be closed ones this fix is merged into the master).

**Comment by Ulfgard** [comment]
I updated to development and still got the same assert

`File "/home/ulfi.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/pproc.py", line 829, in __init__
    assert all(self.evals[0][1:] == 1)  `

**Comment by ttusar** [comment]
Did you run the example experiment again or just the post-processing?

**Comment by Ulfgard** [comment]
just the post-processing. is there a change in coco.c/coco.h as well?

**Comment by Ulfgard** [comment]
can confirm it with updated coco.c/coco.h

**Comment by Ulfgard** [comment]
okay, using an updated coco.c and rerunning the experiment solved this.
