### ISSUE TITLE
postprocessing fails because "bestalg" cannot be imported during call to pickle.py

### ISSUE THREAD

**Issue by tobiaswagner** [numbbo/coco#602]
On my PC (Windows 7, cygwin64, python 2.7.10), the following error occurs, even 
though "python do.py install-postprocessing" ran through without any warnings and the pickle file is available. 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/__main__.py", line 287, in <module>
    rungeneric.main(args)
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/rungeneric.py", line 278, in main
    + ["-o", outputdir, alg])
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/rungeneric1.py", line 354, in main
    outputdir, genericsettings.verbose)
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/ppfigdim.py", line 516, in main
    bestalg.loadBestAlgorithm(dsList.isBiobjective())
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/bestalg.py", line 485, in loadBestAlgorithm
    loadBestBiobj2016()
  File "/home/wagner/.local/lib/python2.7/site-packages/bbob_pproc-0.7b0-py2.7.e                                                                                                                                                                                               gg/bbob_pproc/bestalg.py", line 476, in loadBestBiobj2016
    bestbiobjalgentries2016 = pickle.load(fid)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1069, in load_inst
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named bestalg

**Comment by nikohansen** [comment]
Can't we just remove the `bestalg` facilities in the biobjective case for the time being?

**Comment by dtusar** [comment]
Why he has problems but the others don't?

**Comment by nikohansen** [comment]
I don't know, but at the moment the `bestalg` feature is rather meaningless in the biobj case anyway. We do not have the data to generated a meaningful `bestalg` at this point in time (and in any near future). Additionally, the pickle files should go away (replaced by a different format) on a medium time scale. What would be the reason to stick to this now?

**Comment by dtusar** [comment]
OK, maybe we can remove the use of the `bestalg` in the bi-objective case. But then we have problems with the figures `pplogloss` and tables `pptable`, `pptable2` and `pptables` because they all use the best algorithm data.

**Comment by nikohansen** [comment]
I believe we have anyway a problem in these tables, because the best data are not available for all targets. 

Having said that, if we would create a virtual best algorithm (as this is the case, I believe, in the single-objective `pplogloss` and table computations), this problem would be properly solved. 

The virtual best algorithm is generated from the reference set, by choosing for each time step $t$ the combination of $t$ points with the maximal hyper-volume. See also #557

**Comment by dtusar** [comment]
Now the `bestalg` is not used anymore for the bi-objective case, i.e. `pplogloss` figures are not generated and the values in the tables are not divided by `bestalg`. 

When we will have enough data to create a good virtual best algorithm we will use it again.
