### ISSUE TITLE
install-postprocessing crashes when unexpected folders are present

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#672]
When trying to install the post-processing, additional folders (such as my local `ppdata`) in the `latex-templates/` folder are not allowed and crash the installation which definitely should be avoided:

```
C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho>python do.py install-postprocessing
EXPAND  code-postprocessing\setup.py.in to code-postprocessing\setup.py
PYTHON  setup.py install --user in code-postprocessing
ERROR: return value=1
running install
running bdist_egg
running egg_info
writing bbob_pproc.egg-info\PKG-INFO
writing top-level names to bbob_pproc.egg-info\top_level.txt
writing dependency_links to bbob_pproc.egg-info\dependency_links.txt
reading manifest file 'bbob_pproc.egg-info\SOURCES.txt'
writing manifest file 'bbob_pproc.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying bbob_pproc\bwsettings.py -> build\lib\bbob_pproc
copying bbob_pproc\config.py -> build\lib\bbob_pproc
copying bbob_pproc\genericsettings.py -> build\lib\bbob_pproc
copying bbob_pproc\grayscalesettings.py -> build\lib\bbob_pproc
copying bbob_pproc\ppfigdim.py -> build\lib\bbob_pproc
copying bbob_pproc\ppfigparam.py -> build\lib\bbob_pproc
copying bbob_pproc\pprldistr.py -> build\lib\bbob_pproc
copying bbob_pproc\pproc.py -> build\lib\bbob_pproc
copying bbob_pproc\pptable.py -> build\lib\bbob_pproc
copying bbob_pproc\rungeneric2.py -> build\lib\bbob_pproc
copying bbob_pproc\comp2\ppscatter.py -> build\lib\bbob_pproc\comp2
copying bbob_pproc\compall\ppfigs.py -> build\lib\bbob_pproc\compall
creating build\lib\latex-templates
copying bbob_pproc\..\latex-templates\bbob.bib -> build\lib\bbob_pproc\..\latex-templates
error: can't copy 'bbob_pproc\..\latex-templates\ppdata': doesn't exist or not a regular file

Traceback (most recent call last):
  File "do.py", line 723, in <module>
    main(sys.argv[1:])
  File "do.py", line 699, in main
    elif cmd == 'install-postprocessing': install_postprocessing()
  File "do.py", line 191, in install_postprocessing
    python('code-postprocessing', ['setup.py', 'install', '--user'])
  File "C:\Users\dimo\Desktop\numbbo-github\numbbo-newcococode-brockho\code-experiments\tools\cocoutils.py", line 127, in python
    universal_newlines=True)
  File "C:\Users\dimo\Anaconda\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Users\\dimo\\Anaconda\\python.exe'
, 'setup.py', 'install', '--user']' returned non-zero exit status 1
```

**Comment by brockho** [comment]
see also #518

**Comment by nikohansen** [comment]
This should also be considered as a bug in the testing procedure, because, if I am not mistaken, all the tests passed smoothly.

**Comment by dtusar** [comment]
Fixed by copying only the files that we need.
