### ISSUE TITLE
Nightly build crashes on postprocessing test

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#807]
snippet from the CI:
```
PYTHON        __main__.py all in code-postprocessing/bbob_pproc
ERROR: return value=1
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Using grayscale settings.
Post-processing (1): will generate output data in folder ppdata\test-postprocessing
  this might take several minutes.
Input file or folder C:\builds\workspace\Coco-experiments-devel-nightly-win\dotype\test-postprocessing could not be found.
Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\ci\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0.8b0-py2.7.egg\bbob_pproc\__main__.py", line 296, in <module>
    rungeneric.main(args)
  File "C:\Users\ci\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0.8b0-py2.7.egg\bbob_pproc\rungeneric.py", line 282, in main
    + ["-o", outputdir, alg])
  File "C:\Users\ci\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0.8b0-py2.7.egg\bbob_pproc\rungeneric1.py", line 286, in main
    raise Usage(txt)
bbob_pproc.rungeneric1.Usage
WARNING: this tests the post-processing and doesn't run anything else
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
python -m  bbob_pproc --no-svg --settings=grayscale --conv <https://ci.inria.fr/numbbo/job/Coco-experiments-devel-nightly-win/dotype=test-postprocessing%20all,label=numbbo-win32bitwithjremingw/ws/code-postprocessing\bbob_pproc\data\BFGS_ros_noiseless.tgz>
('**  subtest 1 finished in ', 0.5309998989105225, ' seconds')
Traceback (most recent call last):
  File "__main__.py", line 292, in <module>
    main(args)
  File "__main__.py", line 163, in main
    assert result == 0, 'Test failed: rungeneric on one algorithm with option --conv.'
AssertionError: Test failed: rungeneric on one algorithm with option --conv.

Traceback (most recent call last):
  File "do.py", line 749, in <module>
    main(sys.argv[1:])
  File "do.py", line 741, in main
    test_postprocessing(True) if len(args) > 1 and args[1] == 'all' else test_postprocessing()
  File "do.py", line 564, in test_postprocessing
    python('code-postprocessing/bbob_pproc', ['__main__.py', 'all'])
  File "<https://ci.inria.fr/numbbo/job/Coco-experiments-devel-nightly-win/dotype=test-postprocessing%20all,label=numbbo-win32bitwithjremingw/ws/code-experiments\tools\cocoutils.py",> line 127, in python
    universal_newlines=True)
  File "C:\Anaconda\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Anaconda\\python.exe', '__main__.py', 'all']' returned non-zero exit status 1

<https://ci.inria.fr/numbbo/job/Coco-experiments-devel-nightly-win/dotype=test-postprocessing%20all,label=numbbo-win32bitwithjremingw/ws/>exit> 1
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by dtusar** [comment]
It works now.
