### ISSUE TITLE
R test fails on Mac

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#95]
```
I guess the reason is that I somehow didn't update the R installation of COCO. 
This is what I do:  

./do test

[...]
* checking for sufficient/correct file permissions ... OK
* checking whether package 'coco' can be installed ... ERROR
Installation failed.
See './build/r/pkg.Rcheck/00install.out' for details.

Traceback (most recent call last):
  File "./do.py", line 285, in <module>
    main(sys.argv[1:])
  File "./do.py", line 279, in main
    elif cmd == 'test': test()
  File "./do.py", line 227, in test
    test_r()
  File "./do.py", line 174, in test_r
    run('build/r', ['R', 'CMD', 'check', 'pkg'])
[...]
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['R', 'CMD', 'check', 'pkg']' returned 
non-zero exit status 1


more build/r/pkg.Rcheck/00install.out

* installing *source* package 'coco' ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  
-I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC 
 -Wall -mtune=core2 -g -O2  -c coco.c -o coco.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  
-I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC 
 -Wall -mtune=core2 -g -O2  -c numbbo.c -o numbbo.o
src/numbbo_internal.h:11:66: warning: declaration of 'struct numbbo_problem' 
will not be visible outside of this function [-Wvisibility]
typedef void (*numbbo_initial_solution_function_t) (const struct numbbo_problem 
*self,
                                                                 ^
src/numbbo_internal.h:13:52: warning: declaration of 'struct numbbo_problem' 
will not be visible outside of this function [-Wvisibility]
typedef void (*numbbo_evaluate_function_t) (struct numbbo_problem *self,

```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 27 Feb 2015 at 2:55

**Comment by brockho** [comment]
Is this still relevant, now that we do not support R with the new code for the time being?
